<?php
/**
 * @var $block \Digicel\DisplayLogo\Block\Digicel
 */
?>

<?php $catCollection = $block->getCatCollection(); 
      $mediaUrl = $block->getMediaUrl();
?>
<?php if ($catCollection): ?>    
    <div class="brand-logo">
        <ul class="display-logo">
            <?php foreach ($catCollection as $category): ?>
            <li>
                <a href="<?php echo $category->getUrl()?>"><img src = "<?php echo $mediaUrl.'catalog/category/'.$category->getData('image')?>"></a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
<style>
    .display-logo li {
    float:left;
    list-style-type: none;
    margin-left: 279px;
    padding: 0;
    overflow: hidden;
    display: block;
    text-align: center;
    padding: 16px;
    text-decoration: none;
}
</style>
<?php endif; ?>
