<?php 
$order = $block->getOrder();
$taxData = $block->getTax();
$taxHeader = '';
$taxValue = '';
$taxTotal = '';
$orderSummary = '';

    $payment = $order->getPayment();
    $method = $payment->getMethodInstance();
    $methodTitle = $method->getTitle();
	
	
/* Tax Data */
foreach($taxData as $tax){

	$taxHeader .= '<th style="width: 25%;">'.$tax['title'].' (Tax - '.round($tax['tax_percent']).'%)</th>';
	$taxValue  .= '<td style="width: 25%;">$ '.$tax['real_amount'].'</td>';
	$taxTotal  += $tax['real_amount'];
	$orderSummary .= '<p> '.$tax['title'].'(Tax - '.round($tax['tax_percent']).'%) : $ '.$tax['real_amount'].'</p>';
}

	$totall = $order->getGrandTotal();
	$items  = $order->getAllVisibleItems();
	$shippingAddress = $order->getShippingAddress();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	
?>

<p>Order placed on : <?php echo $order->getCreatedAt(); ?></p><br/>
<p style="text-align: right;">Will be deliver in 1 working days</p>

<?php 
foreach($items as $item) {
		$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
		$imagewidth = 200;
		$imageheight = 200;
		$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
		$image_url = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imagewidth, $imageheight)->getUrl();
		$desc   = 	$_product->getData('description');
		$qty = $item->getQtyOrdered();
    ?>
	
	<table>
	  <tr>
		<th style="width: 50%;"><img class="orderimg" src="<?php echo $image_url;?>" title="<?php echo $_product->getName();?>">
		<p><?php echo $_product->getName(); ?></p></th>
		<th style="width: 50%;"><p style="font-size: 10px;"><?php echo $desc; ?></p></th>
	  </tr>
	</table>
	
	<?php }
	
	?>
	<table>
	  <tr>
	  <th style="width: 25%;">Qty</th>
		<th style="width: 25%;"><?php echo $_product->getName();?></th>
		<?php echo $taxHeader; ?>
		<th style="width: 25%;">Total</th>
	   </tr>
		<tr>
			<td><?php echo round($qty);?></td>
			<td>$ <?php echo $_product->getPrice();?></td>
			<?php echo $taxValue;?>
			<td>$ <?php echo $taxTotal+$_product->getPrice();?></td>
		</tr>
		<tr>
			<td ></td>
			<td ></td>
			<td ></td>
			<td >Shipping Charges</td>
			<td>$ 0.00</td>
		</tr>
	   <tr>
			<td ></td>
			<td ></td>
			<td ></td>
			<td >Total</td>
			<td>$ <?php echo $totall;?></td>
	   </tr>
	</table>
	  <br/>
	  
	  
	  
<div class='shippingArea'><h3>Payment Details</h3>
    <p>Type :<?php echo $methodTitle; ?></p>
</div>
 
<div class='shippingArea'><h3>Shipping Details</h3>
	<p><?php echo $shippingAddress->getFirstname();?> </p>
	<p><?php echo $shippingAddress->getEmail();?> </p>
	<p><?php echo $shippingAddress->getCity();?></p>
	<p>Mob: +507 <?php echo $shippingAddress->getTelephone(); ?></p>
</div>

<div class='shippingArea'><h3>Order Summary</h3>
   <p>Sub Total :<?php echo $_product->getPrice(); ?></p>
   <p>Shipping & Handling : Free</p>
   <?php echo $orderSummary; ?>
   <p>Total : <?php echo $totall;?></p>
</div>

<br/>
<p>Contact DigiCel customer care to change shipping address. Call us at 010101010</p><br/>
	

<?php 
	echo '<div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue btn-action" href="'.$block->getContinueUrl().'"><span>'.__('My Account').'</span></a>
        </div>
		<div class="primary">
            <a class="action primary continue btn-action" href="'.$block->getContinueUrl().'"><span>'.__('Continue Shopping').'</span></a>
        </div>
    </div>';
?>

