<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$productSku = "";
if ($block->getProduct()) {
    $productSku = $block->getProduct()->getSku();
}

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Choose a Smartphone + SIM Plan:');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Choose a Smartphone + SIM Plan:');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>
<?php if ($exist): ?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
            <?php else: ?>
                <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
                <?php endif; ?>
            <?php else: ?>
                <div class="block <?= /* @escapeNotVerified */ $class ?>">
                <?php endif; ?>
                <div class="block-title title">
                    <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
                </div>
                <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
                    <?php if ($type == 'related' && $canItemsAddToCart): ?>
                        <div class="block-actions">
                            <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
                            <button type="button" class="action select" role="select-all"><span><?= /* @escapeNotVerified */ __('select all') ?></span></button>
                        </div>
                    <?php endif; ?>
                    <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
                        <ol class="products list items product-items">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?php $available = ''; ?>
                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <?php $available = 'related-available'; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($type == 'related' || $type == 'upsell'): ?>
                                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li style="width: 35%;" id="plan_' . $_item->getId() . '" class="item product product-item plan_detail" plan_id = "' . $_item->getPlanId() . '" style="display: none;">' : '</li><li style="width: 35%;" id="plan_' . $_item->getId() . '" class="item product product-item plan_detail" plan_id = "' . $_item->getPlanId() . '" style="display: none;">' ?>

                                <?php else: ?>
                                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li  style="width: 35%;" id="plan_' . $_item->getId() . '" class="item product product-item plan_detail">' : '</li><li style="width: 35%;" id="plan_' . $_item->getId() . '" class="item product product-item plan_detail">' ?>
                                <?php endif; ?>
                                <div class="product-item-info <?= /* @escapeNotVerified */ $available ?>">
                                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                                    <a href="javascript:void(0)" class="product photo product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="javascript:void(0)">
                                                <?= $block->escapeHtml($_item->getName()) ?></a>
                                        </strong>
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link"  title="<?= $block->escapeHtml($_item->getId()) ?>" href="javascript:void(0)">
                                                Smartphone Price:<span class="device_price_upsel"></span></a>
                                        </strong>

                                        <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                            <?php if (!$_item->getRequiredOptions()): ?>
                                                <div class="field choice related">
                                                    <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                                    <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if ($showAddTo || $showCart): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                        type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>

                                                <?php if ($showAddTo): ?>
                                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $product = $block->getProduct();
        $sku = array();
        if($product) {
            $productTypeInstance = $product->getTypeInstance();
            $children = $productTypeInstance->getUsedProducts($product);            
            foreach ($children as $child) {  
                $sku[] = $child->getSku();
            } 
            $currency = $objectManager->get('\Magento\Directory\Model\Currency');
            $currency_symbol = $currency->getCurrencySymbol();
        }
        ?>
	<script>
	require([
		'jquery',
		'Magento_Ui/js/modal/modal'
	], function ($, modal) {
		var optionsVal = {
			type: 'popup',
			responsive: true,
			innerScroll: false,
		};
		//Check Session for any post paid is their
		$(document).ready(function () {
			var device_price = $('.product-info-price .price-wrapper').attr('data-price-amount');
			var price_data = {price: device_price};
			$.ajax({
				url: "<?php echo $block->getBaseUrl() . 'port/Addupsell/Checkquote' ?>",
				dataType: 'json',
				showLoader: true,
				type: 'post',
				data: price_data,
				success: function (data) {
					if (data.product_id) {
						$("#port_div").html(data.upsel_data);
						$('#product-options-wrapper').show();
						$('#product-addtocart-button').prop('disabled', false);
					}
				}
			});
		});
		//Show Hide the portability option
		$('#product-options-wrapper').hide();

		$('.upsell').hide();
		var upsel_device_price = $('.product-info-price .price').html();
		$('.device_price_upsel').html(upsel_device_price);
		//portability click function already product in cart
		$(".portable").on('click', function () {
			var portable = $(this).val();
			var port_remove = '';
			var current_service = '';
			var buy_smartphone = '';
			var product_id = '';
            var productsku = '';
            <?php if(isset($sku[0])): ?>
                var productsku = '<?php echo $sku[0] ?>';
                var currency = '<?php echo $currency_symbol ?>';
            <?php endif; ?>            
			if (portable == 'yes') {
				var portable_data = {product_id: product_id, port: portable, port_remove: port_remove, current_service: current_service, buy_smartphone: buy_smartphone,productsku:productsku};
				$.ajax({
					url: "<?php echo $block->getBaseUrl() . 'port/index/index' ?>",
					dataType: 'json',
					showLoader: true,
					type: 'post',
					data: portable_data,
					success: function (data) {
						if (data.result == true) {
                            if(data.price != '') {
                                $('.product-info-price .price').text(currency+data.price);
                            }
							$("#port_div").hide();
							$("#service_div").show();
							$("#port_div_session").hide();
						} else {
							$("#port_div").hide();
							$("#service_div").hide();
							$("#port_div_session").show();
						}
					}
				});
			} else {
				$("#port_div_session").hide();
				$("#port_div").hide();
				$("#contract_div").show();
			}
		});
		//portable remove click function
		$("input[type=radio][name=port_remove]").on('click', function () {
			var port_remove = $(this).val();
			if (port_remove == 'yes') {
				window.location.href = "<?php echo $block->getBaseUrl() . 'checkout/cart' ?>";
			} else {
				$("#port_div_session").hide();
				$("#port_div").hide();
				$("#contract_div").show();
			}
		});
		//Check current service 
		$(".service").on('click',function () {
			if($(this).val() == 'prepaid'){
				$("#service_div").hide();
				$("#contract_div").show();
			}else{
				$("#service_div").hide();
				//$('#product-options-wrapper').show();
				//$('.upsell').show();
				$("#contract_div").show();
			}
		});
		//Check contract service 
		$(".contract").on('click',function () {
			if($(this).val() == 'contract'){
				var contract = 'yes';
				var contract_remove ='';
				var buy_smartphone = '';
				var product_id = '';
				var portable = $('input[name=portable]:checked').val();
				var current_service = $('input[name=service]:checked').val();
				var port_remove = $('input[name=port_remove]:checked').val();		
		        var productsku = '';
                <?php if(isset($sku[0])): ?>
                    var productsku = '<?php echo $sku[0] ?>';
                    var currency = '<?php echo $currency_symbol ?>';
                <?php endif; ?>
				var portable_data = {product_id: product_id,contract: contract,port: portable,contract_remove: contract_remove,port_remove: port_remove,current_service: current_service,buy_smartphone: buy_smartphone,productsku:productsku};
				$.ajax({
				url: "<?php echo $block->getBaseUrl() . 'port/index/index' ?>",
				dataType: 'json',
				showLoader: true,
				type: 'post',
				data: portable_data,
				success: function (data) {
					if(data.result == true) {
                        if(data.price != '') {
                            $('.product-info-price .price').text(currency+data.price);
                        }
						$("#contract_div_session").hide();
						$("#contract_div").hide();
						$('#product-options-wrapper').show();
						$('#contract_option').show();
						$('.upsell').show();
					} else {
						$("#contract_div_session").show();
						$("#contract_div").hide();
					}
				}
				});
			} else {
                var productsku = '';
                <?php if(isset($sku[0])): ?>
                    var productsku = '<?php echo $sku[0] ?>';
                    var currency = '<?php echo $currency_symbol ?>';
                <?php endif; ?>
				$("#contract_div").hide();
				$('#product-options-wrapper').show();
				$('.upsell').show();

			}
		});
	
		//Contract remove click function
		$("input[type=radio][name=contract_remove]").on('click',function () {
			var contract_remove = $(this).val();
			if(contract_remove == 'yes'){
				window.location.href = "<?php echo $block->getBaseUrl() . 'checkout/cart' ?>";
			} else {
				$("#contract_div").hide();
				$("#contract_div_session").hide();
				$('#product-options-wrapper').show();
				$('.upsell').show();
			}
		});
	
        //Credit Check Details show hide popup
        $("#credit_yes").on('click',function () {
            $('#bundle_port').hide();
            $('.Cedula').show();
		});

        $("#Cedula_btn").on('click',function () {
            $('.passport_div').hide();
            $('.cedula_div').show();
			$('#credit_check_btn').show();
        });
         $("#Passport_btn").on('click',function () {
            $('.passport_div').show();
            $('.cedula_div').hide();
			$('#credit_check_btn').show();
        });
        //Credit Check Function Get Data
        $("#credit_check_btn").on('click',function () {
           
            var device_price = $('.product-info-price .price-wrapper').attr('data-price-amount');
            var pid = $(".plan_detail").attr('id');
            var sid = pid.split("_");
            var product_id = sid[1];
            var credit_data = {price: device_price,product_id: product_id};
            $.ajax({
                url: "<?php echo $block->getBaseUrl() . 'port/Addupsell/Credit' ?>",
                dataType: 'json',
                showLoader: true,
                type: 'post',
                data: credit_data,
                success: function (data) {
                    if(data.upsel_data){
						$('#credit_check').hide();
						$('#credit_check').modal("closeModal");
						$("#port_div").html(data.upsel_data);
                        $('#port_div').show();
                        $('.upsell').hide();
                    } 
                }
            });
		});
        //Choose Plan - Upsell Product Selection Dynamic Price Change option
        $(".plan_detail").on('click',function () {
			//Credit Check Popup Open
            if ($("#contract_yes").prop("checked") && $('input[name=contract_remove]:checked').val() != 'no') {
                var popupData = modal(optionsVal, $('#credit_check'));
                $("#credit_check").css("display", "block");
                $('#credit_check').modal('openModal');
				$(".modal-footer").hide();
            }
			//Select Upsell Product
            $(".plan_detail").css("border", "2px solid");
			var pid = $(this).attr('id');
			var sid = pid.split("_");
			var sdiv = '#product-price-'+sid[1];
            $('#upsell_id').val(sid[1]);       //upsell productId
			var plan_price = $(sdiv).attr('data-price-amount');
			var device_price = $('.product-info-price .price-wrapper').attr('data-price-amount');
			var total_price = parseFloat(plan_price) + parseFloat(device_price);
			//Price Calculation
			if(typeof total_price === 'number'){	
				if(total_price % 1 === 0){
					var result = '$' + total_price +'.00';
				} else {
					var result = '$' + total_price;
				    }
			} else {
				var result = '$' + device_price;
			}
			$(this).css("border", "5px solid #136105");
			$('.product-info-price .price').html(result);
			$('#product-addtocart-button').prop('disabled', false); //Enable cart btn
		/// fetch handset API price
			var transType = $('#contract_no').val();
			if (transType == "prepaid") {
				transType = 0;
			}
			if (planType = "postpaid") {
				transType = 1;
			} else {
				transType = 2;
			}
			var productSku = "<?php echo $productSku; ?>";
			var planId = $(this).attr('plan_id');

			var handset_data = {PlanID: planId, Trans_Type: transType, SKU_ID: productSku};
			$.ajax({
				url: "<?php echo $block->getBaseUrl() . 'handsetprice/' ?>",
				dataType: 'json',
				showLoader: true,
				type: 'post',
				data: handset_data,
				success: function (data) {

					if (typeof data === 'number') {
						if (data % 1 === 0) {
							var result = '$' + data + '.00';
						} else {
							var result = '$' + data;
						}
					} else {
						var result = '$' + data;
					}
					$('.product-info-price .price').html(result);
					$('#handset_api_price').val(data);
//                            if (data.upsel_data) {
//                                $('#credit_check').hide();
//                                $('#credit_check').modal("closeModal");
//                                $("#port_div").html(data.upsel_data);
//                                $('#port_div').show();
//                                $('.upsell').hide();
//                            }
				}
			});
		});
	});
</script>
