<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php $_loggedin = $this->helper('Magento\Checkout\Helper\Cart')->getCart()->getCustomerSession()->isLoggedIn(); ?>
<div class="top-sec">
    <aside>
        <nav>
            <ul>
                <li><a href="https://api.whatsapp.com/send?l=es&phone=50760050000"><?php echo __('Whatsapp') ?></a></li>

                <li><a href="<?php echo $block->getUrl('checkout/cart', ['_secure' => true]); ?>"><?php echo __('Cart') ?></a></li>
                <li>
                    <a href="javascript:void(0)"><?php echo __('My Digicel') ?></a>
                    <ul>
                        <?php if (!$_loggedin): ?>
                            <li><a href="<?php echo $this->getUrl('customer/account/login'); ?>"><?php echo __('Login') ?></a></li>
                        <?php endif; ?>
                        <li><a href="<?php echo $this->getUrl('customer/account/'); ?>"><?php echo __('MyAccount') ?></a></li>
                        <?php if ($_loggedin) : ?>
                            <li><a href="<?php echo $this->getUrl('customer/account/logout'); ?>"><?php echo __('logout') ?></a></li>                        <?php endif; ?>

                    </ul>
                </li>
            </ul>
        </nav>
        <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/stores.phtml")->toHtml(); ?>
    </aside>
    <a href="#">Business</a>
</div>
<!-- Header Top Section -->
<!-- Header Middle Section -->
<div class="mid-sec">

    <aside class="mob-menu-sec">

        <div class="mob-menu">
            <a href="javascript:void(0)" class="fas fa-bars" onclick="toggleMenu('pgnav')"></a>
        </div>
    </aside>

    <div class="logo"><a href="<?php echo $this->getBaseUrl(); ?>"></a></div>

</div>
<?php /* switch ($block->getShowPart()):
  case 'welcome': ?>
  <li class="greet welcome" data-bind="scope: 'customer'">
  <!-- ko if: customer().fullname  -->
  <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().firstname)">
  </span>
  <!-- /ko -->
  <!-- ko ifnot: customer().fullname  -->
  <span data-bind='html:"<?= $block->escapeHtmlAttr($welcomeMessage) ?>"'></span>
  <?= $block->getBlockHtml('header.additional') ?>
  <!-- /ko -->
  </li>
  <script type="text/x-magento-init">
  {
  "*": {
  "Magento_Ui/js/core/app": {
  "components": {
  "customer": {
  "component": "Magento_Customer/js/view/customer"
  }
  }
  }
  }
  }
  </script>
  <?php break; ?>

  <?php case 'other': ?>
  <?= $block->getChildHtml() ?>
  <?php break; ?>

  <?php endswitch; */ ?>
