<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php
$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
$helper = $this->helper('Magento\Search\Helper\Data');

//$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
//$urlArray = array('contact-us', 'faqs.html', 'locate');
//$isActive = false;
//foreach ($urlArray as $url) {
//    if (strpos($urlInterface->getCurrentUrl(), $url) !== false) {
//        $isActive = true;
//    }
//}
?>

<div class="bottom-sec">
    <div class="menu-sec">
        <nav data-action="navigation" id="pgnav">
            <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
                <?= /* @escapeNotVerified */ $_menu ?>
                <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
                <li>
                    <a href="javascript:void(0)" >
                        <?php echo __("Support") ?>
                    </a>
                    <ul >
                        <li>
                            <a href="<?php echo $this->getBaseUrl(); ?>" >
                                <?php echo __("Blog") ?>
                            </a>
                        </li>

                        <li >
                            <a href="<?php echo $this->getBaseUrl() . "contact-us"; ?>" >
                                <?php echo __("Contact Us") ?>
                            </a>
                        </li>

                        <li >
                            <a href="<?php echo $this->getBaseUrl() . "faqs.html"; ?>" >
                                <?php echo __("FAQ") ?>
                            </a>
                        </li>

                        <li >
                            <a href="<?php echo $this->getBaseUrl() . "locate"; ?>" >
                                <?php echo __("Locate Store") ?>
                            </a>
                        </li>
                    </ul>
                </li>
                <li><a href="javascript:void(0)" onclick="toggleMenu('pgnav')"><?php echo __("Close X") ?></a></li>
            </ul>
        </nav>
        <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">



            <input id="search"
                   data-mage-init='{"quickSearch":{
                   "formSelector":"#search_mini_form",
                   "url":"<?= /* @escapeNotVerified */ $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]) ?>",
                   "destinationSelector":"#search_autocomplete"}
                   }'
                   type="text"
                   name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                   value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                   placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                   class="input-text search-box"
                   maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                   role="combobox"
                   aria-haspopup="false"
                   aria-autocomplete="both"
                   autocomplete="off"/>
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <?= $block->getChildHtml() ?>
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                </button>
        </form>
    </div>
</div>

<script>
localStorage.setItem('mobmenuClicked', 'FALSE');

var pageNav = document.getElementById('pgnav');

/*  Setting mobile menu display based on window resize  */
document.getElementsByTagName("BODY")[0].onresize = function(){

    var browserSize = {
      width: window.innerWidth || document.body.clientWidth,
      height: window.innerHeight || document.body.clientHeight
    }
    
    if(browserSize.width >= 1200){
        document.getElementById('pgnav').style.display = 'block';
        localStorage.setItem('mobmenuClicked', 'FALSE');
    }else{
        
        if(localStorage.getItem('mobmenuClicked') == 'FALSE'){
            document.getElementById('pgnav').style.display = 'none';
        }
        else{
            if(pageNav.style.display == 'none' || pageNav.style.display == '')
                pageNav.style.display = 'none';
        }
    }
}

/*  Toggle of mobile menu   */
function toggleMenu(navId){
    var navObj = document.getElementById(navId);

    navObj.style.display = (navObj.style.display == 'none' || navObj.style.display == '') ? 'block' : 'none';
    
    localStorage.setItem('mobmenuClicked', 'TRUE');
}
</script>



