<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Customer\Block\Widget\Name */
$x='data-validate="{required:true}"';
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$customerId = $customerSession->getCustomer()->getId();


$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('panama_address');
$sql = $connection->select()->from(["tn" => $tableName])->group('province_id')->order('province_name ASC');
$result = $connection->fetchAll($sql);

$customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($customerId);
		$address_data = $customerObj->getAddresses();
		foreach ($address_data as $address)
		{
			$addressData = $address->toArray();
		}
		
?> 
			<input type="hidden" name="Province" id="Province">
			<input type="hidden" name="District" id="District">
			<input type="hidden" name="Zone_Barrio" id="Zone_Barrio"> 
	<?php
	if($customerSession->isLoggedIn())
	{ ?>
		<div class="field Province required">
			<label for="Province_edit" class="label"><span><?php echo $block->escapeHtml(__('Province')) ?></span></label>
			<div class="control">
				<select id="Province_edit" name="Province_edit" <?php echo $x; ?>>
					<option value="">Select Province</option>
					<?php foreach($result as  $option_val){
						if($addressData['region'] == $option_val['province_name']){$sel = 'selected';}else{$sel = '';}
							echo "<option ".$sel." value='".$option_val['province_id']."'>".$option_val['province_name']."</option>";
                        } ?>
				</select>
			</div>
		</div>			
		<div class="field required">
                <label for="District_edit" class="label"><span><?php echo $block->escapeHtml(__('District')) ?></span></label>
                <div class="control">
                     <select id="District_edit" name="District_edit" <?php echo $x; ?>>
						<option value="">Select District</option>
					</select>
                </div>
        </div>
		<div class="field Zone_Barrio required">
			<label for="Zone_Barrio_edit" class="label"><span><?php echo $block->escapeHtml(__('Zone / Barrio')) ?></span></label>
			<div class="control">
				<select id="Zone_Barrio_edit" name="Zone_Barrio_edit" <?php echo $x; ?>>
					<option value="">Zone / Barrio</option>
				</select>
			</div>
		</div>
		
	<?php } ?>								
	<?php
	if(!$customerSession->isLoggedIn())	{ ?>
		<div class="field Province required">
                <label for="Province_edit" class="label"><span><?php echo $block->escapeHtml(__('Province')) ?></span></label>
                <div class="control">
                    <select id="Province_edit" name="Province_edit" <?php echo $x; ?>>
						<option value="">Select Province</option>
						<?php foreach($result as  $option_val){
							echo "<option value='".$option_val['province_id']."'>".$option_val['province_name']."</option>";
                        } ?>
					</select>
                </div>
            </div>
			<div class="field required">
                <label for="District_edit" class="label"><span><?php echo $block->escapeHtml(__('District')) ?></span></label>
                <div class="control">
                     <select id="District_edit" name="District_edit" <?php echo $x; ?>>
						<option value="">Select District</option>
					</select>
                </div>
            </div>
            <div class="field Zone_Barrio required">
                <label for="Zone_Barrio_edit" class="label"><span><?php echo $block->escapeHtml(__('Zone / Barrio')) ?></span></label>
                <div class="control">
                    <select id="Zone_Barrio_edit" name="Zone_Barrio_edit" <?php echo $x; ?>>
						<option value="">Zone / Barrio</option>
					</select>
                </div>
            </div>
<?php } ?>
<script type="text/javascript">
require([
'jquery', // jquery Library
'jquery/ui', // Jquery UI Library
'jquery/validate', // Jquery Validation Library
'mage/calendar', // Calender
'mage/translate' // Magento text translate (Validation message translte as per language)
], function($){
	$('#District_edit').change(function(){
		var dist = $('#District_edit').val();
		var optionText = $("#District_edit option:selected").text();
		$('#District').val(optionText);		
		$.ajax({
      type: "POST",
      url: "<?php echo $block->getBaseUrl() . 'logincheckout/Login/Address' ?>",
      data: { district: dist },
      success: function (result) {
           $('#Zone_Barrio_edit').html(result);
          }
      });
    });
    $('#Province_edit').change(function(){
		var Prov = $('#Province_edit').val();
		var optionText = $("#Province_edit option:selected").text();
		$('#Province').val(optionText);	
		$.ajax({
      type: "POST",
      url: "<?php echo $block->getBaseUrl() . 'logincheckout/Login/Address' ?>",
      data: { Province: Prov},
      success: function (result) {
           $('#District_edit').html(result);
          }
      });
    });
	$('#Zone_Barrio_edit').change(function(){
		var optionText = $("#Zone_Barrio_edit option:selected").text();
		$('#Zone_Barrio').val(optionText);	
	});
	
});
</script>

