<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
 
 if($block->getCustomer()->getCustomAttribute('mobile_prefix_address')){
    $mprefix = $block->getCustomer()->getCustomAttribute('mobile_prefix_address')->getValue();
}else{
    $mprefix = '';
}

?>
<style>
 .field-mobile_prefix_address{display:none;}
</style>
<div class="col-lg-12">
<form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
   <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>"/>
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>"/>
        <div style="display:none;"><?php echo $block->getNameBlockHtml() ?></div>
<div class="row">
<div class="col-md-6 col-sm-6 col-xs-12 ">
<?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
<div class="col-md-3 col-sm-12 col-xs-12 pl0">
							 <label class="Login_form_Txt pull-left"><?php /* @escapeNotVerified */ echo __('Street Address') ?></label>
</div>
<div class="col-md-12 col-sm-12 col-xs-12 pl0 mart0 pr0"> 
    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="form-control input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"/>
	 <div class="nested">
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 3, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <div class="field additional">
                        <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"/>
                        </div>
                    </div>
                <?php endfor; ?>
</div>
</div>
</div>

<div class="col-md-6 col-sm-6 col-xs-12  city required">
<div class="col-md-3 col-sm-12 col-xs-12 pl0">
		<label class="Login_form_Txt pull-left"><?php /* @escapeNotVerified */ echo __('City') ?></label>
</div>
<div class="col-md-12 col-sm-12 col-xs-12 pl0 mart0 pr0"> 
<input type="text" name="city" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text form-control <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city" />
</div>          
</div>
</div>
<div class="row">
 <div class="col-md-6 col-sm-6 col-xs-12 country required">
 <div class="col-md-3 col-sm-12 col-xs-12 pl0">
		<label class="Login_form_Txt pull-left"><?php /* @escapeNotVerified */ echo __('Country') ?></label>
</div>
<div class="col-md-12 col-sm-12 col-xs-12 pl0 mart0 pr0">            
            
                <?php echo $block->getCountryHtmlSelect() ?>
</div>            
</div>
<div class="col-md-6 col-sm-6 col-xs-12 zip required">
 <div class="col-md-3 col-sm-12 col-xs-12 pl0">
		<label class="Login_form_Txt pull-left"><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></label>
</div>
<div class="col-md-12 col-sm-12 col-xs-12 mart0 pl0 pr0">  
<input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text form-control integer validate-not-negative-number" minlength="5" maxlength="5" />
</div>           
 </div>		
</div>
<div class="row">
<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
	$attribute = $eavConfig->getAttribute('customer', 'mobile_prefix');
	$options = $attribute->getSource()->getAllOptions();
?>
 <div class="col-md-6 telephone required">
  <div class="col-md-3 col-sm-12 col-xs-12 pl0">
		<label class="Login_form_Txt pull-left"><?php /* @escapeNotVerified */ echo __('Phone Number') ?></label>
</div>
<div class="row clearfix">
<div class="col-md-3">
			<select  id="mobile_prefix_address" name="mobile_prefix_address"   title="mobile_prefix_address"
				class="mobiledrop required-entry<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('mobile_prefix_address') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> >
				<?php foreach ($options as $_option): ?>
				<?php if($_option['value'] != ''){

				?>
			   
				<option value="<?php /* @escapeNotVerified */ echo $_option['value'] ?>"<?php if ($mprefix == $_option['label']): ?> selected="selected"<?php endif; ?>>
				 <?php /* @escapeNotVerified */ echo __($_option['label']) ?>
				  </option>
				<?php } ?>
				<?php endforeach; ?>
        </select>
</div>
<div class="col-md-9">		
	            <input  type="text" minlength="10"  maxlength="10" name="telephone" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="form-control input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>"  id="telephone" data-validate="{required:true,'validate-digits':true,minlength:'10',maxlength:'10', 'validate-mobile-number':true}"/>
</div>
      </div>     
       
</div>	
 <div class="col-md-6 preference required">
 <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_address_user_attributes'); ?>
        <?php if ($userDefinedAttributes):?>
            <?php echo $userDefinedAttributes->setShowContainer(true)->toHtml(); ?>
        <?php endif;?>		
 </div>
   </div> 
	<div class="col-md-12 col-sm-12 col-xs-12 pl0  pr0">
	<fieldset class="fieldset">      
        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?php /* @escapeNotVerified */ echo __("This is your default billing address.") ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
        <div class="field choice set billing">
            <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox"/>
            <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
        </div> 
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?php /* @escapeNotVerified */ echo __("This is your default shipping address.") ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox"/>
                <label class="label" for="primary_shipping"><span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1"/>
        <?php endif; ?>
    </fieldset>
	</div>
    <div class="col-md-5 col-md-offset-4 col-sm-12 col-xs-12 mb20 pl0 text-center">
        <div class="primary">
            <button type="submit" class="btn btn-default btnVibee width100" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?php /* @escapeNotVerified */ echo __('Go back') ?></span>
            </a>
        </div>
    </div>
</form>
<script>
       require([
    'jquery',
    'mage/validation'
], function($){

    var dataForm = $('#form-validate');
    var ignore = null;

    dataForm.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

   
	$('#telephone').blur( function() {
		
		$.validator.validateElement($("#telephone"));
    });
	
	$("#street_1").autocomplete({
		source: function (request, response) {
			$.ajax({
				url: "<?php echo $block->getBaseUrl(); ?>laposte/index/Addresslist",
				data: { q: request.term },
				dataType: "json",
				success: function (data) {
					response(data);
					$('.street > .control > span.ui-helper-hidden-accessible'). hide();
				}
			});
		},
		minLength: 2,
		select: function( event, ui ) {
			$.ajax({
				url: "<?php echo $block->getBaseUrl(); ?>laposte/index/Addressdetails",
				data: { address_code: ui.item.code },
				dataType: "json",
				success: function (addressDetails) {
					$("#street_1").val(addressDetails.numeroVoie + ' ' + addressDetails.libelleVoie);
					$("#street_1").trigger('change');
					$("#city").val(addressDetails.commune);
					$("#city").trigger('change');
					$("#zip").val(addressDetails.codePostal);
					$("#zip").trigger('change');
				}
			});
		}
	});
});
    </script>
<script type="text/javascript">
require([
'jquery', 
'jquery/ui', 
'jquery/validate', 
'mage/translate' 
], function($){
	$.validator.addMethod(
		'validate-mobile-number', function (value) {
			var str = $('#telephone').val();

			if (!str.match(/^[0]?[67]\d{8}$/)) {
				return false;
			}
			return true;
		}, '<?php echo __('Please specify a valid mobile number.');?>');	
});
</script>
	
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
</div>
<style>
.preference fieldset{
width:100% !important;
}
.field-address_preference label{
	margin:15px 0px 4px 0px !important;
}
.mart0{
margin-top:0px !important;
}
.ui-autocomplete {
  position: absolute;
  left: 0;
  z-index: 1000;
  float: left;
  display: none;
  min-width: 160px;
  _width: 160px;
  -padding: 4px 0;
  margin: 35px 0 0 0 !important;
    border-radius: 0px !important;
  border:1px solid #00f !important;
  -padding:10px;
  list-style: none;
  background-color: #ffffff;
  border-color: #ccc;
  border-color: rgba(0, 0, 0, 0.2);
  border-style: solid;
  border-width: 1px;
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -webkit-background-clip: padding-box;
  -moz-background-clip: padding;
  background-clip: padding-box;
  *border-right-width: 2px;
  *border-bottom-width: 2px;

  .ui-menu-item > a.ui-corner-all {
    display: block;
    padding: 3px 15px;
    clear: both;
    font-weight: normal;
    line-height: 18px;
    color: #555555;
    white-space: nowrap;

    &.ui-state-hover, &.ui-state-active {
      color: #ffffff;
      text-decoration: none;
      background-color: #0088cc;
      border-radius: 0px;
      -webkit-border-radius: 0px;
      -moz-border-radius: 0px;
      background-image: none;
    }
  }
}
/* Autocomplete
----------------------------------*/
.ui-autocomplete { position: absolute; cursor: default; }       
.ui-autocomplete-loading { background: white url('images/ui-anim_basic_16x16.gif') right center no-repeat; }

/* workarounds */
* html .ui-autocomplete { width:1px; } /* without this, the menu expands to 100% in IE6 */

/* Menu
----------------------------------*/
.ui-menu {
        list-style:none;
          padding: 0px !important;
        margin: 0;
        display:block;
        width:227px;
}
.ui-menu .ui-menu {
        margin-top: -3px;
}
.ui-menu .ui-menu-item {
        margin:0;
        padding: 0;
        width: 200px;
}
.ui-menu .ui-menu-item a {
        text-decoration:none;
        display:block;
        padding:.2em .4em;
        line-height:1.5;
        zoom:1;
		color:#00f !important;
		cursor:pointer;
}
.ui-menu .ui-menu-item a.ui-state-hover,
.ui-menu .ui-menu-item a.ui-state-active {
        margin: -1px;
}
.ui-menu .ui-menu-item{
padding:5px 0;
}
.ui-helper-hidden-accessible{
display:none;
}
.ui-menu .ui-menu-item {
    padding: 5px 10px;
    border-bottom: 1px solid blue;
    width: 100%;
}
ui-autocomplete-loading { background:url("../images/address_2_icon.png") no-repeat right center }

 .ui-state-hover, .ui-widget-content .ui-state-hover, .ui-widget-header .ui-state-hover, .ui-state-focus, .ui-widget-content .ui-state-focus, .ui-widget-header .ui-state-focus, .ui-menu .ui-menu-item a:hover {
    cursor: pointer;
    color: red !important;
}
</style>
	