<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
if($block->getCustomer()->getCustomAttribute('mobile_number')){
    $mobile=$block->getCustomer()->getCustomAttribute('mobile_number')->getValue();
}else{
    $mobile='';
}
if($block->getCustomer()->getCustomAttribute('mobile_prefix')){
    $mprefix = $block->getCustomer()->getCustomAttribute('mobile_prefix')->getValue();
}else{
    $mprefix = '';
}

?>
<h3 class="page-title mt10 pl15 pr15"><?php echo $block->escapeHtml(__('Account Information')) ?></h3>
<div class="col-md-12">
<form class="form form-edit-account" action="<?php echo $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <div class="account-info">
        <?php echo $block->getBlockHtml('formkey')?>
		<div class="item">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
		<div class="clearfix"></div>
		</div>
		<div class="item">
			<div class="form-left">
				<?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
				<?php $newsletterblock = $block->getLayout()->createBlock('Digicel\Customeraccount\Block\Customer\Newsletter') ?>
				<?php if ($_dob->isEnabled()): ?>
					<?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
				<?php endif ?>
			</div>
			<div class="form-right">
				<?php
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
				$attribute = $eavConfig->getAttribute('customer', 'mobile_prefix');
				$options = $attribute->getSource()->getAllOptions();
				?>
				<div class="field field-name-mobile required">
				<?php //echo 'prefix--'. $block->getCustomer()->getData('mobile_prefix');?>
					<label class="label" for="mobile">
						<span><?php echo $block->escapeHtml(__('Mobile Number')) ?></span>
					</label>
					<div class="clearfix">
					<div class="form-left">
					<select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
            name="mobile_prefix"
            title="mobile_prefix"
            class="mobiledrop required-entry<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('mobile_prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> >
            <?php foreach ($options as $_option): ?>
			<?php if($_option['value'] != ''){

			?>
            <!--<option value="<?php /* @escapeNotVerified */ //echo $_option['label']; ?> <?php //if($mprefix == $_option['label'] ) { ?>  selected='selected' <?php //} ?>">
                <?php /* @escapeNotVerified */// echo __($_option['label']) ?>
            </option>-->
			<option value="<?php /* @escapeNotVerified */ echo $_option['label'] ?>" <?php if ($mprefix == $_option['label']): ?> selected="selected"<?php endif; ?>>
			 <?php /* @escapeNotVerified */ echo __($_option['label']) ?>
			  </option>
			<?php } ?>
            <?php endforeach; ?>
        </select>
					</div>
					<div class="form-right">
					<div class="control">
					<input type='text' minlength="10"  maxlength="10" id='mobile_number' name='mobile_number' value="<?php echo $mobile;?>" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" data-validate="{required:true,'validate-digits':true,minlength:'10',maxlength:'10','validate-mobile-number':true}"  class="Login_box form-control input-text required-entry validate-not-negative-number integer" autocomplete="off" />
					</div>
					</div>
				</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="item">
			<div class="form-left">
				<div class="field field-name-email required">
					<label class="label" for="email">
						<span><?php echo $block->escapeHtml(__('Email')) ?></span>
					</label>
					<div class="control">
						<input value="<?php echo $block->getCustomer()->getEmail();?>" id="m2"  disabled="true" type="text">
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="item check-pass-change">
			<div class="field choice">
			   <label class="label pull-left" for="change-password" style="line-height:20px;"><span> <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="pull-left checkbox" style="margin-right:3px;"/>
				<?php echo $block->escapeHtml(__('Change Password')) ?></span></label>
			</div>
			<div class="clearfix"></div>
		</div>
    </div>
	
    <div class="change-password" data-container="change-email-password" style="display:none;">
		<h3 class="mt10 pl15 pr15"><?php echo $block->escapeHtml(__('Change Email and Password')) ?></h3>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?php echo $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?php echo $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php echo $block->escapeHtml(__('Password Strength')); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php echo $block->escapeHtml(__('No Password')); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?php echo $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" onpaste="return false;"  name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </div>
	<?php if ($newsletterblock->isNewsletterEnabled()): ?>
		    <div class="field choice newsletter">
                <h5 class="Login_form_Txt pull-left"><label for="is_subscribed" class="label subscribe"> 
				<input type="checkbox" name="is_subscribed" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed" <?php if ($newsletterblock->getIsSubscribed()): ?> checked="checked" <?php endif; ?> class="pull-left checkbox">
               <span><?php echo $newsletterblock->escapeHtml(__('Send information from SailFish')) ?></span></label></h5>
			 
            </div>
			 <div class="field choice clearfix">
                <h5 class="Login_form_Txt pull-left" style="margin:1px 0;"><label for="is_partner_subscribed" class="label subscribe"> 
				<input type="checkbox" name="is_partner_subscribed" title="" value="1" id="is_partner_subscribed"<?php if ($newsletterblock->getIsPartnerSubscribed()): ?> checked="checked"<?php endif; ?> class="pull-left checkbox">
              
			   <span><?php echo $newsletterblock->escapeHtml(__('Send information from other partners')) ?></span></label></h5>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $newsletterblock->getChildHtml('customer.form.register.newsletter')?>
		
    <?php endif ?>
    <div class="actions-toolbar">
		<div class="primary">
			<button type="submit" class="action save primary" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Save')) ?>"><span><?php echo $block->escapeHtml(__('Save')) ?></span></button>
		</div>
		<div class="secondary">
			<a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo $block->escapeHtml(__('Go back')) ?></span></a>
		</div>
	</div>
</form>
</div>
<style type="text/css">
label.subscribe span{margin-left: 4px;}
</style>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
		var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });
        $('#dob').blur( function() {
		
		$.validator.validateElement($("#dob"));
    });
    });
</script>
<script type="text/javascript">
function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
		  // document.getElementById('m2').value = "";
           return false;

         return true;
      }
</script>
</script>

<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        }
    }
</script>
<script type="text/javascript">
require([
'jquery', // jquery Library
'jquery/ui', // Jquery UI Library
'jquery/validate', // Jquery Validation Library
'mage/translate' // Magento text translate (Validation message translte as per language)
], function($){
	$.mage.translate.add(<?php
		echo \Zend_Json::encode(
				array(
				    "Please enter valid name." => __("Please enter valid name.")
				                        
				)
		);?>);
$.validator.addMethod(
'validate-french-name', function (value) { 
return /^[a-zA-Z-ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ '']+$/i.test($.trim(value));
}, $.mage.__('Please enter valid name.'));
});
</script>
<script>
    require([
    'jquery',
            'Magento_Ui/js/modal/modal',
			'mage/template',
			'mage/mage',
			'jquery/validate',
			'jquery/ui',
			'mage/translate'
], function($){
	$('#dob').change( function() {
		var dobval =$('#dob').val();
		var data = { dobval:dobval,
				   };
		$.ajax({ 
		url:"<?php echo $this->getBaseUrl().'biil/index/account'?>",
		dataType: 'text',
		type : 'post',
		data: data,
		success: function(data){
			if(data == 0)
			{
			    document.getElementById("doberrr").innerHTML = $.mage.__('Your DateOfBirth must be greater than 18 years')
				return false;
														
			}
			else
			{
				document.getElementById("doberrr").innerHTML = '';
			}
		}
		}); 
	});

	$.validator.addMethod(
		'validate-mobile-number', function (value) {
			var str = $('#telephone').val();

			if (!str.match(/^[0]?[67]\d{8}$/)) {
				return false;
			}
			return true;
		}, '<?php echo __('Please specify a valid mobile number.');?>');
});
</script>
