<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
 
if($block->getCustomer()->getCustomAttribute('mobile_number')){
    $mobile = $block->getCustomer()->getCustomAttribute('mobile_number')->getValue();
}else{
    $mobile='';
}


if($block->getCustomer()->getCustomAttribute('mobile_prefix')){
    $mprefix = $block->getCustomer()->getCustomAttribute('mobile_prefix')->getValue();
}else{
    $mprefix = '';
}

if($block->getCustomer()->getCustomAttribute('cedulla')){
    $cedulla = $block->getCustomer()->getCustomAttribute('cedulla')->getValue();
	
}else{
    $cedulla='';
}

if($block->getCustomer()->getCustomAttribute('passport')){
    $passport=$block->getCustomer()->getCustomAttribute('passport')->getValue();
}else{
    $passport='';
}

if($block->getCustomer()->getCustomAttribute('dob')){
    $dob=$block->getCustomer()->getCustomAttribute('dob')->getValue();
}else{
    $dob='';
}

?>

<div class="col-md-12">
<form class="form form-edit-account" action="<?php echo $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php echo __('* Required Fields') ?>" autocomplete="off">
    <div class="account-info">
        <?php echo $block->getBlockHtml('formkey')?>
		<div class="item">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
		<div class="clearfix"></div>
		</div>
		<div class="item">
			<div class="form-left">
				<?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
				<?php //$newsletterblock = $block->getLayout()->createBlock('Digicel\Customeraccount\Block\Customer\Newsletter') ?>
				<?php if ($_dob->isEnabled()): ?>
					<?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
				<?php endif ?>
			</div>
			<div class="form-right">
				<?php
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
				$attribute = $eavConfig->getAttribute('customer', 'mobile_prefix');
				$options = $attribute->getSource()->getAllOptions();
				?>
				
				<div class="field field-name-mobile required">
				
					<label class="label" for="mobile">
						<span><?php echo $block->escapeHtml(__('Mobile Number')) ?></span>
					</label>
					<div class="clearfix">
					<div class="form-left">
					<select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
						name="mobile_prefix"
						title="mobile_prefix"
						class="mobiledrop required-entry<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('mobile_prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> >
						<?php foreach ($options as $_option): ?>
						<?php if($_option['value'] != ''){

						?>
						
						<option value="<?php /* @escapeNotVerified */ echo $_option['label'] ?>" <?php if ($mprefix == $_option['label']): ?> selected="selected"<?php endif; ?>>
						 <?php /* @escapeNotVerified */ echo __($_option['label']) ?>
						  </option>
						<?php } ?>
						<?php endforeach; ?>
					</select>
					</div>
					<div class="form-right">
					<div class="control">
					<input type='text' id='mobile_number' name='mobile_number' value="<?php echo $mobile;?>" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" data-validate="{required:true, 'validate-mobile-number':true, 'mobile-maxleng':true}"  class="Login_box form-control input-text required-entry validate-not-negative-number integer" autocomplete="off" />
					</div>
					</div>
				</div>
				</div>
				
			</div>
			<div class="clearfix"></div>
		</div>
		
		<div class="item">
			<div class="form-left">
				<div class="field field-name-email required">
					<label class="label" for="email">
						<span><?php echo $block->escapeHtml(__('Email')) ?></span>
					</label>
					<div class="control">
						<input value="<?php echo $block->getCustomer()->getEmail();?>" id="m2"  disabled="true" type="text">
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="item">
			<div class="form-left">
				<div class="field field-name-cedulla required">
					<label class="label" for="cedulla">
						<span><?php echo $block->escapeHtml(__('Cedulla')) ?></span>
					</label>
					<div class="control">
						<input value="<?php echo $cedulla ;?>" id="cedulla" type="text" maxlength="20">
					</div>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="form-left">
				<div class="field field-name-cedulla required">
					<label class="label" for="cedulla">
						<span><?php echo $block->escapeHtml(__('Passport')) ?></span>
					</label>
					<div class="control">
						<input value="<?php echo $passport;?>" id="passport" type="text" maxlength="20">
					</div>
				</div>
			</div>
		</div>
		
		<div class="control">
						<label><?php echo $block->escapeHtml(__('Personal ID')) ?></label>
					</div>
							<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
								$cedulla = $eavConfig->getAttribute('customer', 'cedulla');
								?>
					<div class="field required">
						<div class="control-">
							<input type="button" value="Cedulla" onclick="myFunction()">
						</div>
					</div>
					<div class="field required" id="sidecontainer" style="display:none">
					<table style="width:100%">
					  <tr>
						<th class="field Province required"><label class="label"><?php echo __('Province') ?> </label></th>
						<th class="field Letterss required"><label class="label"><?php echo __('Letterss') ?> </label></th> 
						<th class="field I take required"><label class="label"><?php echo __('I take') ?> </label></th>
						<th class="field Seat required"><label class="label"><?php echo __('Seat') ?> </label></th>
						<th class="field Number required"><label class="label"><label class="label"><?php echo __('Number') ?> </label></th>
					  </tr>
					  <tr>
					  		<td><div class="formitem">
							<select name="province" id="state" class="input-text" data-validate="{required:true, 'validate-customer-province':true}">
							  <option value="1">1</option>
							  <option value="2">2</option>
							  <option value="3">3</option>
							  <option value="4">4</option>
							  <option value="5">5</option>
							  <option value="6">6</option>
							  <option value="7">7</option>
							  <option value="8">8</option>
							  <option value="9">9</option>
							  <option value="10">10</option>
							  <option value="11">11</option>
							  <option value="12">12</option>
							  <option value="13">13</option>
							</select>
						</div></td>
						<td><div class="formitem">
							<select name="letters" id="city" class="input-text" data-validate="{required:true, 'validate-customer-letters':true}">
							  <option value="PI">PI</option>
							  <option value="AV">AV</option>
							  <option value="E">E</option>
							  <option value="N">N</option>
							  <option value="PE">PE</option>
							  <option value="P">P</option>
							</select>
						</div></td> 
						<td><div class="formitem">
							<input type="text" maxlength="6" autocomplete="u1"  name="itake" title="<?php echo __('I Take') ?>" id="street" placeholder="" class="form-control Login_box input-text required-entry" data-validate="{required:true, equalTo:'#cedulla'}" autocomplete="off">
						</div></td>
						<td><div class="formitem">
							<input type="text" maxlength="6" autocomplete="u1"  name="seat" title="<?php echo __('Seat') ?>" id="zip" placeholder="" class="form-control Login_box input-text required-entry" data-validate="{required:true, equalTo:'#cedulla'}" autocomplete="off">
						</div></td>
						<td><div class="formitem">
							<input type="text" maxlength="6" autocomplete="u1"  name="cedulla" title="<?php echo __('Number') ?>" id="latlongaddress" placeholder="" class="form-control Login_box input-text required-entry" data-validate="{required:true, equalTo:'#cedulla'}" autocomplete="off">
						</div></td>
					  </tr>
					</table>
					</div>
					<label class="Login_form_Txt pull-left"><?php echo __('OR') ?></label></br>
					<div class="field required">
						<label class="Login_form_Txt pull-left"><?php echo __('Passport') ?> </label>
						<div class="control-">
							<input type="text" autocomplete="u1"  name="passport" title="<?php echo __('Passport') ?>" id="passport" placeholder="" class="form-control Login_box input-text required-entry" data-validate="{required:true, 'validate-passport':true, 'passport-maxleng':true}" autocomplete="off">
						</div>
					</div>
		
		<div class="item check-pass-change">
			<div class="field choice">
			   <label class="label pull-left" for="change-password" style="line-height:20px;"><span> <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="pull-left checkbox" style="margin-right:3px;"/>
				<?php echo $block->escapeHtml(__('Change Password')) ?></span></label>
			</div>
			<div class="clearfix"></div>
		</div>
    </div>
	
    <div class="change-password" data-container="change-email-password" style="display:none;">
		<h3 class="mt10 pl15 pr15"><?php echo $block->escapeHtml(__('Change Email and Password')) ?></h3>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $block->getCustomer()->getEmail(); ?>" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?php echo $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?php echo $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php echo $block->escapeHtml(__('Password Strength')); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php echo $block->escapeHtml(__('No Password')); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?php echo $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" onpaste="return false;"  name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </div>

	<div class="shipping-div">
		<table style="height: 134px;" width="700" border="0">
			<tbody>
				<tr>
					<th class="Shipping-Address"><label class="label"><?php echo __('Shipping Address') ?> </label></th>
				</tr>
				<tr style="height: 53px;">
				<td style="width: 372px; height: 53px;">
				<p>Province</p>
				<div class="formitem">
					<select id="state" class="input-text" style="width: 200px;" name="province" data-validate="{required:true, 'validate-customer-province':true}">
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
					<option value="5">5</option>
					<option value="6">6</option>
					<option value="7">7</option>
					<option value="8">8</option>
					<option value="9">9</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>
					<option value="13">13</option>
					</select>
				</div>
				</td>
				<td style="width: 377px; height: 53px;">
				<p>Disctrict</p>
				<div class="formitem">
					<select id="city" class="input-text" style="width: 200px;" name="letters" data-validate="{required:true, 'validate-customer-letters':true}">
					<option value="PI">PI</option>
					<option value="AV">AV</option>
					<option value="E">E</option>
					<option value="N">N</option>
					<option value="PE">PE</option>
					<option value="P">P</option>
					</select>
				</div>
				</td>
				</tr>
				<tr style="height: 69px;">
				<td style="width: 372px; height: 69px;">
				<p>Zone/Bario</p>
				<div class="formitem">
					<select id="city" class="input-text" style="width: 200px;" name="letters" data-validate="{required:true, 'validate-customer-letters':true}">
					<option value="PI">PI</option>
					<option value="AV">AV</option>
					<option value="E">E</option>
					<option value="N">N</option>
					<option value="PE">PE</option>
					<option value="P">P</option>
					</select>
				</div>
				</td>
				<td style="width: 377px; height: 69px;">
				<p>Address</p>
				<p><input type="text" /></p>
				</td>
				</tr>
				<tr style="height: 69px;">
				<td style="width: 372px; height: 69px;">
				<p>Direction Indications</p>
				<p><input type="text" /></p>
				</td>
				<td style="width: 377px; height: 69px;">&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="subscription">
		 <table class="data table " id="my-table">
			<tbody>
                <tr>
                    <td scope="col" class="col one">
						<div class="clearfix mt52 row">
							<h3><?php echo __('Newsletter Subscription') ?></h3>
							<div class="fontRed GothamMedium11 col-md-offset-3">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pl30 ">
									<label class="mb0 chkboxcontainer">
									<input type="checkbox" name="is_subscribed" title="<?php echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" class="pull-left checkbox" checked="checked"><?php echo __('Send Information from DigiCel') ?>
									<span class="checkmark"></span>
									</label>
								</div>	
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-left pl30 ">
									<label class="mb0 chkboxcontainer GothamMedium11">
									<input type="checkbox" name="is_partner_subscribed" title="" value="1" id="is_partner_subscribed"  checked="checked" class="pull-left checkbox"><?php echo __('Send Information from other partners') ?>
									 <span class="checkmark"></span>
									</label>
								</div>
								
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-left pl30">
									<label class="mb0 chkboxcontainer">
									<input type="checkbox" name="is_contracts_subscribed" title="" value="1" id="is_contracts_subscribed" checked="checked" class="pull-left checkbox" onclick="return false;">
									<?php echo __('Send me Contract and Invoices') ?>
									<span class="checkmark"></span></label>
								</div>
								
							</div>  
						</div>
					</td>
                    <td scope="col" class="col two">
						<div class="clearfix mt52 row">
							<div class="fontRed GothamMedium11 col-md-offset-3">
								<h3><?php echo __('Newsletter Subscription for Holder') ?></h3>
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pl30 ">
									<label class="mb0 chkboxcontainer">
									<input type="checkbox" name="is_subscribed" title="<?php echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" checked="checked" class="pull-left checkbox" checked="checked"><?php echo __('Send Information from DigiCel') ?>
									<span class="checkmark"></span>
									</label>
								</div>	
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-left pl30 ">
									<label class="mb0 chkboxcontainer GothamMedium11">
									<input type="checkbox" name="is_partner_subscribed" title="" value="1" id="is_partner_subscribed"  checked="checked" class="pull-left checkbox"><?php echo __('Send Information from other partners') ?>
									 <span class="checkmark"></span>
									</label>
								</div>
								
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-left pl30">
									<label class="mb0 chkboxcontainer">
									<input type="checkbox" name="is_contracts_subscribed" title="" value="1" id="is_contracts_subscribed" checked="checked" class="pull-left checkbox" onclick="return false;">
									<?php echo __('Send me Contract and Invoices') ?>
									<span class="checkmark"></span></label>
								</div>
								
							</div>  
						</div>
					</td>
                </tr>
            </tbody>
		</table>
	</div>
	
    <div class="actions-toolbar">
		<div class="primary">
			<button type="submit" class="action save primary" title="<?php echo __('Save'); ?>"><span><?php echo __('Save') ?></span></button>
		</div>
		<div class="secondary">
			<a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo __('Go back') ?></span></a>
		</div>
	</div>
</form>
</div>
<style type="text/css">
label.subscribe span{margin-left: 4px;}
</style>

<style>
 #sidecontainer div {
  display: inline;
  margin: 0 1em 0 1em;
  width: 10%;
}
</style>

<script>
 function myFunction() {
    var x = document.getElementById("sidecontainer");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

<script type="text/javascript">
    function generateFullName()
    {
			document.getElementById('cedulla').innerText = generateFullName;
            document.getElementById('state').value + ' ' + 
			document.getElementById('city').value + ' ' + 
			document.getElementById('street').value + ' ' + 
			document.getElementById('zip').value + ' ';
            //document.getElementById("number").value = generateFullName;
			
    }
</script>
<script>
require([ 'jquery', 'jquery/ui'], function($){ 
      $('#state,#city,#street,#zip').bind('keypress blur', function() {    
		$('#latlongaddress').val($('#state').val() + '' +
                             $('#city').val() + '' +
                             $('#street').val() + '' +
                             $('#zip').val() );

      });
 });
</script>


<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
		var ignore = <?php /* @escapeNotVerified */ //echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php //if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php //else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php //endif ?>
        });
        $('#dob').blur( function() {
		
		$.validator.validateElement($("#dob"));
    });
    });
</script>

<script type="text/javascript">
function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
		  // document.getElementById('m2').value = "";
           return false;

         return true;
      }
</script>
</script>

<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?php echo __('Change Email') ?>",
                "titleChangePassword": "<?php echo __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?php echo __('Change Email and Password') ?>"
            }
        }
    }
</script>

<script type="text/javascript">
require([
'jquery', // jquery Library
'jquery/ui', // Jquery UI Library
'jquery/validate', // Jquery Validation Library
'mage/translate' // Magento text translate (Validation message translte as per language)
], function($){
	$.mage.translate.add(<?php
		echo \Zend_Json::encode(
				array(
				    "Please enter valid name." => __("Please enter valid name.")
				                        
				)
		);?>);
$.validator.addMethod(
'validate-french-name', function (value) { 
return /^[a-zA-Z-ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ '']+$/i.test($.trim(value));
}, $.mage.__('Please enter valid name.'));
});
</script>
<script>
    require([
    'jquery',
            'Magento_Ui/js/modal/modal',
			'mage/template',
			'mage/mage',
			'jquery/validate',
			'jquery/ui',
			'mage/translate'
], function($){
	$('#dob').change( function() {
		var dobval =$('#dob').val();
		var data = { dobval:dobval,
				   };
		$.ajax({ 
		url:"<?php echo $this->getBaseUrl().'biil/index/account'?>",
		dataType: 'text',
		type : 'post',
		data: data,
		success: function(data){
			if(data == 0)
			{
			    document.getElementById("doberrr").innerHTML = $.mage.__('Your DateOfBirth must be greater than 18 years')
				return false;
														
			}
			else
			{
				document.getElementById("doberrr").innerHTML = '';
			}
		}
		}); 
	});

	$.validator.addMethod(
		'validate-mobile-number', function (value) {
		if(!value.match(/^[0-9]+$/)) { 
			return false;
		}
		return true;
	}, '<?php echo __('Please specify a valid mobile number.');?>');
	
	$.validator.addMethod("mobile-maxleng", function(value) {
		if(value.length>8 && value.length<8) {
			return false;
		}
		return true;
	}, $.mage.__('mobile number should be 8 digit'));
	
	$.validator.addMethod(
		'validate-passport', function (value) {
		if(!value.match(/^[a-zA-Z0-9]+$/)) {
			return false;
		}
		return true;
	}, '<?php echo __('Please enter valid passport number');?>');
	
	$.validator.addMethod("passport-maxleng", function(value) {
		if(value.length>9 && value.length<9) {
			return false;
		}
		return true;
	}, $.mage.__('Passport number should be 9 character'));
});
</script>
