<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="user-form-container forgot-pwd-container">
    <header>Reset Your Password</header>
    <div class="user-form">
        <h1>If you've forgotten your password or want to change it,you can easily do it here.</h1>

        <h2>Enter your valid Email address associated with your account. We will send you the password link to your valid e-Mail address.</h2>
        <form class="form password forget"
              action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>
          
                <div class="field email required form-element">
                    <label for="email_address" class="label lbl"><span><?= $block->escapeHtml(__('Email address')) ?>*</span></label>
                  
                        <input type="email" name="email" alt="email" id="email_address" class="input-text elm" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                    
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
           
            <div class="actions-toolbar account-btn">
                
                    <button type="submit" class="action submit primary primary-btn"><span><?= $block->escapeHtml(__('Reset')) ?></span></button>
                
               <?php /* <div class="secondary">
                    <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                </div>
                */ ?>
                
            </div>
        </form>
    </div>
</div>