<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $block \Magento\Customer\Block\Address\Book
 */
?>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
$Address = $objectManager->get('\Magento\Customer\Api\Data\AddressInterface');
$attribute = $eavConfig->getAttribute('customer_address', 'address_preference');
//echo get_class($block);
?>
<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12 pull-right marT25">
<div class="col-lg-8 col-md-6 col-sm-12 col-xs-12">
<div class="block block-addresses-default">

    <div class="block-content">
        <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
		    <div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					    <img src="<?php echo $this->getViewFileUrl('images/address_color_flow.png'); ?>" class="pull-left">	
						<h4 class="pull-left article_title fontBear"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><?php echo __('billing addresses'); ?></font></font></h4>
					</div>
			</div>
			
            <div class="billing">			                
                <div class="box-content">                    
                    <?php  
                        $defaultBil = $objectManager->create('Magento\Customer\Model\Address')->load($_pAddsses);
						$street= $defaultBil->getStreet();
						$countryName = $defaultBil->getCountryModel()->getName();
					?>
					
					<?php 
						// update what ever you want    				
                        $addressPreference = $defaultBil->getCustomAttribute('address_preference');
                        if(isset($addressPreference) && is_object($addressPreference)) {
                            $optionId = $defaultBil->getCustomAttribute('address_preference')->getValue();
                            $optionText = $attribute->getSource()->getOptionText($optionId); ?>
                            <span style="font-size:15px;!important;"><b><?php //echo $optionText.'Address'; ?> </b></span>
                        <?php } ?><br />                    

                        <?php //echo $block->getAddressHtml($block->getAddressById($_pAddsses));  ?>
                    
					<div class="col-md-12 col-sm-9 col-xs-12 bgWhite pb20 pl0 pr0">						
						<div class="greyline pl15 pr15 pb10">							
							<!-- First Row -->
							<div class="clearfix">
								<div class="col-md-6 col-sm-12 col-xs-12">
									<label><?php /* @escapeNotVerified */ echo __('Street Address') ?></label>
									<input type="text" class="form-control" placeholder="<?php echo $street[0]; ?>" value="<?php echo $street[0]; ?>" disabled>
								</div>
								<div class="col-md-6 col-sm-12 col-xs-12">
									<label><?php /* @escapeNotVerified */ echo __('City') ?></label>
									<input type="text" class="form-control" placeholder="<?php echo $defaultBil->getCity(); ?>" value="<?php echo $defaultBil->getCity(); ?>" disabled>
								</div>
								<div class="col-md-6 col-sm-12 col-xs-12">
									<label><?php /* @escapeNotVerified */ echo __('Country') ?></label>
									<input name="country" type="text" class="form-control" placeholder="<?php echo $countryName; ?>" value="<?php echo $countryName; ?>" disabled>																	
								</div>															
								<div class="col-md-6 col-sm-12 col-xs-12">
									<label><?php /* @escapeNotVerified */ echo __('Zip Code') ?></label>
									<input type="text" class="form-control" placeholder="<?php echo $defaultBil->getPostcode();  ?>" value="<?php echo $defaultBil->getPostcode();  ?>" disabled>
								</div>
								<div class="col-md-6 col-sm-12 col-xs-12">
									<label><?php /* @escapeNotVerified */ echo __('Phone number') ?></label>
									<input type="text" class="form-control" placeholder="<?php echo $defaultBil->getTelephone();  ?>" value="<?php echo $defaultBil->getTelephone();  ?>" disabled>
								</div>
								<?php if(isset($optionText)){ ?> 
								<div class="col-md-6 col-sm-12 col-xs-12">
									<label><?php /* @escapeNotVerified */ echo __('Address Preference') ?> </label>
									<input type="text" class="form-control" placeholder="<?php echo  $optionText;  ?>" value="<?php echo  $optionText;  ?>" disabled>
								</div>
								<?php } ?>
							</div>
						</div>						
						<!-- Delivery Address -->
						
					</div>					

                </div>
				<?php /* <div class="box-actions">
                    <a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">
                        <span><?php echo __('Change Billing Address') ?></span>
                    </a>
                </div> */ ?>
            </div>
        <?php else: ?>
            <div class="box box-billing-address">
                <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span></strong>
                <div class="box-content">
                    <p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
                </div>
            </div>
        <?php endif ?>
		<hr class="hr">
		<div class="clearfix"></div>
        <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
            <div class="shipping">
		         <div class="marT25">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<img src="<?php echo $this->getViewFileUrl('images/address_icon.png'); ?>" class="pull-left">	
						<h4 class="pull-left article_title fontBear"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><?php echo __('delivery addresses');?></font></font></h4>
					</div>
				</div>
              
                <div class="box-content">
                   
                    <?php
                    $defaultShip = $objectManager->create('Magento\Customer\Model\Address')->load($_pAddsses);
                    $addressPreference = $defaultShip->getCustomAttribute('address_preference');
					$countryName = $defaultShip->getCountryModel()->getName();
					$streetship= $defaultShip->getStreet();
                    if(isset($addressPreference) && is_object($addressPreference)) {
                        $optionId = $defaultShip->getCustomAttribute('address_preference')->getValue();
                        $optionText = $attribute->getSource()->getOptionText($optionId); ?>
                        <!-- <span style="font-size:15px;!important;"><b><?php echo $optionText; ?> Address</b></span> -->
                    <?php } ?><br/>  
                        <?php //echo $block->getAddressHtml($block->getAddressById($_pAddsses));echo '<br/>'; ?>
                
                </div>
				<div class="col-md-12 col-sm-9 col-xs-12 bgWhite pb20 pl0 pr0">
				<div class="clearfix pl15 pr15">				
				<!-- First Row -->
				<div class="clearfix">
					<div class="col-md-6 col-sm-12 col-xs-12">
						<label><?php /* @escapeNotVerified */ echo __('Street Address')?></label>
						<input type="text" class="form-control" placeholder="<?php echo $streetship[0]; ?>" value="<?php echo $streetship[0]; ?>" disabled>
					</div>
					<div class="col-md-6 col-sm-12 col-xs-12">
						<label><?php /* @escapeNotVerified */ echo __('City')?></label>
						<input type="text" class="form-control" value="<?php echo $defaultShip->getCity(); ?>" disabled>
					</div>
					<div class="col-md-6 col-sm-12 col-xs-12">
						<label><?php /* @escapeNotVerified */ echo __('Country')?> </label>
						<input name="country" type="text" disabled class="form-control" value="<?php echo $countryName; ?>">					
					</div>					
					<div class="col-md-6 col-sm-12 col-xs-12">
						<label><?php /* @escapeNotVerified */ echo __('Phone number')?></label>
						<input type="text" class="form-control" placeholder="<?php echo $defaultShip->getTelephone();  ?>" value="<?php echo $defaultShip->getTelephone();  ?>" disabled>
					</div>										
					<div class="col-md-6 col-sm-12 col-xs-12">
						<label><?php /* @escapeNotVerified */ echo __('Zip Code')?></label>
						<input type="text" class="form-control" placeholder="<?php echo $defaultShip->getPostcode();  ?>" value="<?php echo $defaultShip->getPostcode();  ?>" disabled>
					</div>
					<div class="col-md-6 col-sm-12 col-xs-12">
						<label><?php /* @escapeNotVerified */ echo __('Address Preference')?></label>
						<input type="text" class="form-control" placeholder="<?php echo $optionText; ?>" value="<?php echo $optionText;  ?>" disabled>
					</div>						
				</div>
			</div>			
					
                 <div class="box-actions">
                    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Change Shipping Address') ?></span>
                    </a>
                </div>	 		
			
			</div>											

            </div>
        <?php else: ?>
            <div class="box box-shipping-address">
                <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span></strong>
                <div class="box-content">
                    <p><?php /* @escapeNotVerified */ echo __('You have no default shipping address in your address book.') ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
<div class="clearfix"></div>
<div class="col-md-12 col-sm-9 col-xs-12 bgWhite pb20 pl0 pr0">
<div class="block block-addresses-list">
    <div class="block-title col-lg-12 col-md-12 col-sm-12 col-xs-12">
	<h3 class="article_title"><?php /* @escapeNotVerified */ echo __('Additional Address Entries') ?></h3></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>
            <ol class="items addresses col-md-6">
                <?php foreach ($_pAddsses as $_address): ?>
                   
                    <li class="item" style="width:100%;">
                        <address>
                        <?php 
                        $addressPreference = $_address->getCustomAttribute('address_preference');
                        if(isset($addressPreference) && is_object($addressPreference)) {
                            $optionId = $_address->getCustomAttribute('address_preference')->getValue();
                            $optionText = $attribute->getSource()->getOptionText($optionId); ?>
                            <!-- <span style="font-size:15px;!important;"><b><?php //echo $optionText.'Address'; ?> </b></span> -->
                        <?php } ?>
                            <?php echo $block->getAddressHtml($_address) ?><br />
                        </address>
                        <div class="item actions">
                            <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/address/edit', ['id' => $_address->getId()]) ?>"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
                            <a class="action delete" href="#" role="delete-address" data-address="<?php /* @escapeNotVerified */ echo $_address->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Delete Address') ?></span></a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php else: ?>
            <p class="empty"><?php /* @escapeNotVerified */ echo __('You have no other address entries in your address book.') ?></p>
        <?php endif ?>
    </div>
	<div class="clearfix"></div>
	<div class="actions-toolbar col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="primary">
        <button type="button" role="add-address" title="<?php /* @escapeNotVerified */ echo __('Add New Address') ?>" class="btn btn-default btnVibee width100"><span><?php /* @escapeNotVerified */ echo __('Add New Address') ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
    </div>
</div>
</div>
</div>
</div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "li.item a[role='delete-address']",
                "deleteUrlPrefix": "<?php /* @escapeNotVerified */ echo $block->getDeleteUrl() ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?php /* @escapeNotVerified */ echo $block->getAddAddressUrl() ?>"
            }
        }
    }
</script>
