<?php	?>
<h3 class="mt10 pl15 pr15"><?php /* @escapeNotVerified */ echo __('My Bills') ?></h3>
<div class="iban-content">
	<fieldset class="fieldset">
        <div class="field contract-url">           
            <div class="control"><br>
               <span><?php echo __('Please check the monthly billing info') ?></span>
			   <span class="view-sepa-url">&nbsp;&nbsp;<a target="_blank" href="<?php echo $this->getMonthlyBillUrl(); ?>"><b><?php echo __('Click Here') ?></b></span>
            </div>
        </div>
    </fieldset>
</div>
   
