<?php
$customerSession = $block->getCustomerSession();
$msisdnNumber = $block->getMsisdnNumber();
$msisdnStatus = $block->getMsisdnStatus();

$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
 $customerSession->getCustomer()->getId()."<br/>";  // get Customer Id
 $customerName = $customerSession->getCustomer()->getName()."<br/>";  // get  Full Name
 $customerSession->getCustomer()->getEmail()."<br/>"; // get Email Name
}  
?>

<div class="">
    <table style="height: 148px; width: 901px;" border="1">
		<tbody>
			<tr style="height: 35px;">
				<td style="width: 900px; height: 35px;" colspan="7">Line No: +507 <?php echo $msisdnNumber; ?>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; SIM: 2421-5738-7629-3821</td>
			</tr>
			<tr style="height: 39px;">
				<td style="width: 151px; height: 39px;">&nbsp;Status os the line</td>
				<td style="width: 121px; height: 39px;">&nbsp;Holder Name</td>
				<td style="width: 129px; height: 39px;">&nbsp;Offer Name</td>
				<td style="width: 134px; height: 39px;">&nbsp;Plan</td>
				<td style="width: 127px; height: 39px;">&nbsp;Activation Date</td>
				<td style="width: 137px; height: 39px;">&nbsp;Bill Cycle Date</td>
				<td style="width: 101px; height: 39px;" rowspan="2"><button>Replace SIM</button></td>
			</tr>
			<tr style="height: 39px;">
				<td style="width: 151px; height: 39px;">&nbsp;<?php echo $msisdnStatus;?></td>
        <td style="width: 121px; height: 39px;">&nbsp;<?php echo $customerName;?></td>
				<td style="width: 129px; height: 39px;">&nbsp;<input type="checkbox" />&nbsp;Data Offer</td>
				<td style="width: 134px; height: 39px;">&nbsp;15.99 $</td>
				<td style="width: 127px; height: 39px;">&nbsp;12/02/2018</td>
				<td style="width: 137px; height: 39px;">&nbsp;12/05/2018</td>
			</tr>
		</tbody>
	</table>
</div>