<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>

<div>
<h2>Welcome</h2>
<table style="height: 408px; width: 851px;">
<tbody>
<tr>
<td style="width: 196px;" rowspan="3"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/leftimage.png'); ?>"></a></td>
<td style="width: 437px;"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/myinfo.png'); ?>"></a> </td>
<td style="width: 217px;" rowspan="3"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/my_lines.png'); ?>"></a> </td>
</tr>
<tr>
<td style="width: 437px;"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/my_orders.png'); ?>"></a> </td>
</tr>
<tr>
<td style="width: 437px;"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/right.png'); ?>"></a> </td>
</tr>
</tbody>
</table>
</div>
