<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>

<div>
<h2>Welcome</h2>

<table style="height: 370px; width: 900px;">
	<tbody>
		<tr style="height: 80px;">
			<td style="width: 185px; height: 235px;" rowspan="3"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/leftimage.png'); ?>"></a></td>
			<td style="width: 385px; height: 80px;"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/myinfo.png'); ?>"></a> </td>
			<td style="width: 185px; height: 235px;" rowspan="3"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/right.png'); ?>"></a></td>
		</tr>
			<tr style="height: 80px;">
			<td style="width: 385px; height: 80px;"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/my_lines.png'); ?>"></a></td>
		</tr>
			<tr style="height: 80px;">
			<td style="width: 385px; height: 80px;"><a href=""><img src="<?php echo $this->getViewFileUrl('images/myaccount/my_orders.png'); ?>"></a></td>
		</tr>
	</tbody>
</table>
</div>
