<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>

<div class="myaccount">
    <div class="user-form-container">

        <header class="color_welcome"><?php echo __('Welcome') ?></header>

        <!-- User Registration Form Section -->
        <div class="user-form">
            <div class="flex-container">
                <div class="rectangle1 firstbox">
                    <div class="my-information">
                        <?php echo __('MY INFORMATION') ?>
                    </div>
                </div>
                <div class="rectangle_red">
                    <div class="redbox go-now ">
                        <span class="go-bordr" onclick="window.location.href = '<?php echo $block->getUrl('customer/account/edit/', ['_secure' => true]); ?>'"><?php echo __('GO NOW !') ?></span>
                    </div>
                </div>	
            </div>
            <div class="flex-container mrg-top">
                <div class="rectangle1 firstbox">
                    <div class="my-information">
                        <?php echo __('MY LINE') ?> 
                    </div>
                </div>
                <div class="rectangle_red">
                    <div class="redbox go-now ">
                        <span class="go-bordr" onclick="window.location.href = '<?php echo $block->getUrl('mylines/customer/index/', ['_secure' => true]); ?>'"><?php echo __('GO NOW !') ?></span>
                    </div>
                </div>	
            </div>
            <div class="flex-container mrg-top">
                <div class="rectangle1 firstbox">
                    <div class="my-information">
                        <?php echo __('MY ORDERS') ?>
                    </div>
                </div>
                <div class="rectangle_red">
                    <div class="redbox go-now ">
                        <span class="go-bordr" onclick="window.location.href = '<?php echo $block->getUrl('sales/order/history', ['_secure' => true]); ?>'"><?php echo __('GO NOW !') ?></span>
                    </div>
                </div>	
            </div>
        </div>
    </div>  
</div>