<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoryIds = $product->getCategoryIds();
$category_name = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryIds[0])->getName();
$finalPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
$formattedPrice = $priceHelper->currency($regularPrice, true, false);
?>
<ol>
    <li>
        <div></div>
        <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        <div></div>
    </li>
    <li>
        <h5><?php echo $category_name ?></h5>
        <h4>
            <?= $block->escapeHtml($block->getProductName()) ?>
        </h4>
        <p><?php echo substr($product->getShortDescription(), 0, 50); ?><?php echo '...' ?></p>
    </li>
    <li>
        <?php if ($finalPrice < $regularPrice) {
            $price_percentage = number_format((($regularPrice - $finalPrice) * 100 / $regularPrice),2);
        ?>
            <div>
                Normal
                <strike><?php echo $formattedPrice ?></strike> / <?php echo $price_percentage.'%'; ?>
            </div>
        <?php } ?>
        <div class="offer-price-wrapper">
            <?= $block->getUnitPriceHtml($_item) ?><?php if ($finalPrice < $regularPrice) { ?>(offer)<?php } ?>
        </div>
    </li>
    <li>
        <div class="item-counter">
            <div>
                <button type="button" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-decrease" class="decreaseQty">&#8208;</button>
                <!-- <button>&#8208;</button> -->
            </div>
            <div class="counter-box input-text qty" id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty" name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]" data-cart-item-id="<?= /* @escapeNotVerified */ $_item->getSku() ?>">
                <!-- <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty" name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]" data-cart-item-id="<?= /* @escapeNotVerified */ $_item->getSku() ?>" value="<?= /* @escapeNotVerified */ $block->getQty() ?>" type="number" size="4" title="<?= $block->escapeHtml(__('Qty')) ?>" class="input-text qty counter-box" data-validate="{required:true,'validate-greater-than-zero':true}" data-role="cart-item-qty"/> -->
                <?= /* @escapeNotVerified */ $block->getQty() ?>
            </div>
            <div>
                <button type="button" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-increase" class="increaseQty">&plus;</button>
                <!-- <button>&plus;</button> -->
            </div>
        </div>
        <div class="text-center remove-item-wrapper">
            <div class="actions-toolbar">
                <?= $block->getActions($_item) ?>
            </div>
        </div>
    </li>
    <li><?= $block->getUnitPriceHtml($_item) ?></li>
</ol>
<?php /* <tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= $block->getProductUrl() ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= $helpLinkId ?>","productName": "<?= $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= __("What's this?") ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= $_item->getId() ?>-qty">
                    <span><?= __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?= $_item->getId() ?>-qty"
                           name="cart[<?= $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= $_item->getSku() ?>"
                           value="<?= $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?= $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
<?php </tbody> */ ?>
<script type="text/javascript">
require(["jquery"],function($){
    $('#<?php echo $_item->getId() ?>-increase').click(function(){
        var $this = $(this);
        var item_id = ($(this).attr('id').replace('-increase',''));
        var currentQty = $("#cart-"+item_id+"-qty").text();
        var increase = parseInt(currentQty)+parseInt(1);
        var form_key = $('input[name=form_key]').val();

        // var customeAttri={};
        // customeAttri.address_supplement=supplimentry;
        // cart.custom_attributes=customeAttri; 

        // var form_data = {};
        // form_data.form_key = form_key;
        // var cart={};
        // cart.item_id = item_id;
        // form_data.cartitem_id = 1;

        jQuery.ajax({
            url: "<?php echo $this->getUrl('checkout/cart/updatePost/') ?>",
            type: "POST",
            data: {'form_key':form_key,'cart': item_id,'update_cart_action':'update_qty'},
            // data: form_data,
            success: function(response){
                $("#cart-"+item_id+"-qty").text(increase);
            }
        });
    });
    $('#<?php echo $_item->getId() ?>-decrease').click(function(){
        var $this = $(this);
        var item_id = ($(this).attr('id').replace('-decrease',''));
        var currentQty = $("#cart-"+item_id+"-qty").text();
        if(currentQty > 1) {
            var decrease = parseInt(currentQty)-parseInt(1);
            $("#cart-"+item_id+"-qty").text(decrease);
        }
    });
});
</script>