<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
if($block->getCustomer()->getCustomAttribute('mobile_number')){
    $mobile=$block->getCustomer()->getCustomAttribute('mobile_number')->getValue();
}else{
    $mobile='';
}
if($block->getCustomer()->getCustomAttribute('mobile_prefix')){
    $mprefix = $block->getCustomer()->getCustomAttribute('mobile_prefix')->getValue();
}else{
    $mprefix = '';
}
$firstname =$block->getCustomer()->getFirstName();
$lastname = $block->getCustomer()->getLastName();
$customername = $firstname.' '.$lastname

/* ?>
<style>
.account.page-layout-2columns-left .sidebar-main, .account.page-layout-2columns-left .sidebar-additional {
    width: 25%;
    position: relative;
    min-height: 1px;
    padding-right: 15px;
    padding-left: 15px;
    float: left;
	margin-top:27px;
}
.fontBear {
    text-transform: lowercase !important;
}
.customer-account-index .breadcrumbs>.items>li.home {
    padding-left: 25px !important;
}
.article_action_title a{text-decoration: underline;}
h4.my-info{margin-top:11px !important}
.modifier-button{ margin: 0 3px 0 9px;}
</style><?php */?>
<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12" id="myInformation">
<div class="col-lg-12 col-md-12 col-sm-12 co-xs-12 padL30 mrgTop">
	<h5 class="section_title_small_ttl mt0"><?php echo __('Your information has changed since your last visit, ').ucfirst($customername). '?' ?> </h5>
	<h5 class="section_title_small"><?php echo __('Think about modifying them!');?></h5>
</div>
<div class="col-lg-7 col-md-9 col-sm-12 col-xs-12 marT25">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padL10">
		<img src="<?php echo $this->getViewFileUrl('images/personal_info_my.png'); ?>" class="pull-left">	
		<h4  class="pull-left article_title fontBear"><?php echo __('MY INFORMATION');?></h4>
		<?php /* <h6 class="pull-right article_action_title marT15 pr20"><a href="#?" onclick="showedit();"><img src="<?php echo $this->getViewFileUrl('images/modifier.png'); ?>"><span class="modifier-button"><?php echo __('Modifier');?></span><span class="glyphicon glyphicon-menu-right"></span></a></h6> */?>
	</div>
<form class="form form-edit-account" action="<?php echo $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
	<!-- Form Key -->
    <?php echo $block->getBlockHtml('formkey')?>

	<!-- Name -->
    <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
	
	<!-- DOB -->
	<?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
	<?php if ($_dob->isEnabled()): ?>
		<?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
	<?php endif ?>
	
	<?php $newsletterblock = $block->getLayout()->createBlock('Digicel\Customeraccount\Block\Customer\Newsletter') ?>
	
	<!-- Phone Number -->
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <label class="Login_form_Txt pull-left"><?php echo $block->escapeHtml(__('Mobile Number')) ?>
		<img src="<?php echo $block->getViewFileUrl('images/tooltip_icon.png'); ?>" data-toggle="tooltip" title="" alt="" data-original-title="Ce numéro nous sera utile pour la signature électronique de vos documents et pour vous contacter si nécessaire en attendant l'activation de votre ligne Vibee.Ce numéro doit être au format internation : Indicatif régional + 9 chiffres (ex: 596 696999999)"/>
		</label>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left">
			<div class="col-md-6 col-sm-6 col-xs-6 pl0">
				<?php
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
					$attribute = $eavConfig->getAttribute('customer', 'mobile_prefix');
					$options = $attribute->getSource()->getAllOptions();
				?>
				<select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"       name="mobile_prefix" title="mobile_prefix" class="form-control mobiledrop required-entry<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('mobile_prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> >
					<?php foreach ($options as $_option): ?>
						<?php if($_option['value'] != '') { ?>
            					<option value="<?php /* @escapeNotVerified */ echo $_option['value'] ?>"<?php if ($mprefix == $_option['value']): ?> selected="selected"<?php endif; ?>><?php /* @escapeNotVerified */ echo __($_option['label']) ?></option>
						<?php } ?>
					<?php endforeach; ?>
				</select>
                <i class="select_arrow glyphicon glyphicon-triangle-bottom arrowCont"></i>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-6 pl0 pr0">
				<input type="text" minlength="10" maxlength="10" id='mobile_number' name='mobile_number' placeholder="25 69 88 56 32" value="<?php echo $mobile;?>" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" data-validate="{required:true,'validate-digits':true,minlength:'10',maxlength:'10', 'validate-mobile-number':true}"  class="Login_box input-text required-entry validate-not-negative-number integer form-control" autocomplete="off" />
			</div>
        </div>
    </div>
	
	<!-- Email Address -->
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 read_only">
		<label class="Login_form_Txt pull-left">
		<?php echo $block->escapeHtml(__('EmailAddress')) ?>*</label>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left">
			<input type="text" class="form-control" value="<?php echo $block->getCustomer()->getEmail();?>" id="m2" readonly>
		</div>
	</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="item check-pass-change">
			<div class="field choice">
			   <input  type="checkbox" name="change_password" style="display:none;" id="change-password" data-role="change-password" value="1" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="pull-left checkbox" />
			   <a href="javascript:void(0)" onclick="changepassword();" class="note">
				<?php echo $block->escapeHtml(__('ICI, vous pouvez modifier votre mot de passe')) ?></a>
				<span style="display:none;" class="checkmark"></span>
			</div>
			<div class="clearfix"></div>
		</div>
		</div>

	
    <div class="change-password col-lg-12 col-md-12 col-sm-12 col-xs-12" data-container="change-email-password" style="display:none;">
		<h5 class="mt10 pl15 pr15"><?php echo $block->escapeHtml(__('Change Email and Password')) ?></h5>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 field email required" data-container="change-email">
            <label class="Login_form_Txt pull-left" for="email"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
           <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Email')) ?>" class="form-control input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 field password current required">
            <label class="Login_form_Txt pull-left" for="current-password"><span><?php echo $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left control">
                <input type="password" class="form-control input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="Login_form_Txt pull-left" for="password"><span><?php echo $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left control">
                <input type="password" class="form-control input-text" name="password" id="password"
                    data-password-min-length="<?php echo ($block->getMinimumPasswordLength() != '') ? $block->escapeHtml($block->getMinimumPasswordLength()) : 8; ?>"
                    data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php echo $block->escapeHtml(__('Password Strength')); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php echo $block->escapeHtml(__('No Password')); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 field confirm password required" data-container="confirm-password">
            <label class="Login_form_Txt pull-left" for="password-confirmation"><span><?php echo $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left control">
                <input type="password" class="input-text form-control" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </div>
	<?php if ($newsletterblock->isNewsletterEnabled()): ?>
	<?php $countoredr  = $newsletterblock->getCustomerOrders();?>
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 radio-toolbar marT25">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pl0 pull-left">			 
			<label class="chkboxcontainer">
                
				<input <?php if($countoredr > 0){ echo 'disabled="disabled"';}?> type="checkbox" name="is_subscribed" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed" <?php if ($newsletterblock->getIsSubscribed()): ?> checked="checked" <?php endif; ?> class="pull-left checkbox"/>
                J'accepte de recevoir des informations de Vibee <span class="checkmark"></span></label>
	</div>

		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pl0 pull-left">
              <label class="chkboxcontainer">
               <input <?php if($countoredr > 0){ echo 'disabled="disabled"';}?> type="checkbox" name="is_partner_subscribed" title="" value="1" id="is_partner_subscribed"<?php if ($newsletterblock->getIsPartnerSubscribed()): ?> checked="checked"<?php endif; ?> class="pull-left checkbox"/>
                J’accepte de recevoir des informations de ses partenaires <span class="checkmark"></span> </label>
            </div>			
			
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt-20 pl0 pull-left">
              <label class="chkboxcontainer blueColor">
                <input onclick="return false;" <?php if($countoredr > 0){ echo 'disabled="disabled"';}?> type="checkbox" name="is_contracts_subscribed" title="" value="1" id="is_contracts_subscribed"<?php if ($newsletterblock->getIsContractsSubscribed()): ?> checked="checked"<?php endif; ?> class="pull-left checkbox"/>
                Je reçois mes factures par email <span class="blue_checkmark"></span> </label>
            <?php /* Extensions placeholder */ ?>
            <?php echo $newsletterblock->getChildHtml('customer.form.register.newsletter')?>
		</div></div>
    <?php endif ?>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt-20 mb20 pl0 pull-left" id="saveaction-bar">
		<div class="col-md-4 col-sm-4 col-xs-4 pl0 pull-left">
              <h6 class="article_action_title marT15 login_lnks"><a href="#?" onclick="showedit();"><img src="<?php echo $this->getViewFileUrl('images/modifier.png'); ?>" class="mr-10" alt="">Modifier <span class="glyphicon glyphicon-menu-right"></span></a></h6>
			 
            </div>
		<div class="col-md-4 col-sm-4 col-xs-4 pl0 pr0">
			<button type="submit"  class="btn login_btn btn-lg btn-block" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Save')) ?>"><span><?php echo $block->escapeHtml(__('JE VALIDE')) ?></span></button>
		</div>
		<?php /*<div class="secondary">
			<a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo $block->escapeHtml(__('Go back')) ?></span></a>
		</div>*/?>
	</div>
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 marT25 mb25" >
		<h6 class="tab_content_hdr_detail"><?php echo __('To edit other data in your account,'); ?></h6>
		<h6 class="tab_content_hdr_detail"><?php echo __('contact your customer service via webchat'); ?></h6>
	</div>
</form>
</div>
<div class="col-lg-5 col-md-3 col-sm-12 col-xs-12 hidden-sm mt-big">
		<img class="hand_img_rt" src="<?php echo $this->getViewFileUrl('images/lip_hand.png'); ?>">		
</div>
</div>
<?php
//echo $this->getLayout()
  //        ->createBlock('Digicel\IBAN\Block\Iban\Ibanshow')
    //      ->setTemplate('Digicel_IBAN::ibanshow.phtml')
      //    ->toHtml();
		  ?>
		  
<style type="text/css">
label.subscribe span{margin-left: 4px;}
</style>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
		var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });
        $('#dob').blur( function() {
		
		$.validator.validateElement($("#dob"));
    });
    });
</script>
<script type="text/javascript">
function showedit(){
jQuery('#saveaction-bar').show();
 jQuery('html, body').animate({
        'scrollTop' : jQuery("#saveaction-bar").position().top
    });
}
function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
		  // document.getElementById('m2').value = "";
           return false;

         return true;
      }
</script>
</script>

<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        }
    }
</script>
<script type="text/javascript">
require([
'jquery', 
'jquery/ui', 
'jquery/validate', 
'mage/translate' 
], function($){
	$.mage.translate.add(<?php
		echo \Zend_Json::encode(
				array(
				    "Please enter valid name." => __("Please enter valid name."),
				)
		);?>);

		$.validator.addMethod(
			'validate-french-name', function (value) { 
				return /^[a-zA-Z-ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ '']+$/i.test($.trim(value));
			}, $.mage.__('Please enter valid name.'));

		$.validator.addMethod(
			'validate-french-name-with-space', function (value) { 
				return /^[a-zA-Z-ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ '']+$/i.test($.trim(value));
			}, $.mage.__('Please enter valid name.'));
		
		$.validator.addMethod(
			'validate-mobile-number', function (value) {
				var str = $('#mobile_number').val();

				if (!str.match(/^[0]?[67]\d{8}$/)) {
					return false;
				}
				return true;
			}, '<?php echo __('Please specify a valid mobile number.');?>');
});
</script>
<script>
    require([
    'jquery',
            'Magento_Ui/js/modal/modal',
			'mage/template',
			'mage/mage',
			'jquery/validate',
			'jquery/ui',
			'mage/translate'
], function($){
	$('#dob').change( function() {
		var dobval =$('#dob').val();
		var data = { dobval:dobval,
				   };
		$.ajax({ 
		url:"<?php echo $this->getBaseUrl().'biil/index/account'?>",
		dataType: 'text',
		type : 'post',
		data: data,
		success: function(data){
			if(data == 0)
			{
			    document.getElementById("doberrr").innerHTML = $.mage.__('Your DateOfBirth must be greater than 18 years')
				return false;
														
			}
			else
			{
				document.getElementById("doberrr").innerHTML = '';
			}
		}
		}); 
	});
	$(function () {
		$('[data-toggle="tooltip"]').tooltip()
		$("#Floating_tab_menu").hide();
	});
	});

</script>
<script>
function myFunction() {
    document.getElementById("formFieldset").disabled = false;
}
function changepassword() {    
	jQuery("input#change-password").click();
}
</script>