<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$checkoutSession = $objectManager->get('Magento\Catalog\Model\Session');
echo "port ->".$checkoutSession->getPort().'<br>';
echo "current_service ->".$checkoutSession->getCurrentService().'<br>';
echo "buy_smartphone->".$checkoutSession->getBuySmartphone();

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php if($_product->getTypeId() == 'bundle'): ?>javascript:void(0)<?php else: ?><?= /* @escapeNotVerified */ $_product->getProductUrl() ?> <?php endif; ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php if($_product->getTypeId() == 'bundle'): ?>javascript:void(0)<?php else: ?><?= /* @escapeNotVerified */ $_product->getProductUrl() ?> <?php endif; ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>						
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
										<?php if($_product->getTypeId() == 'bundle'): ?>
											<a id="bundle_add_cart-<?php echo $_product->getId(); ?>" class="bundle_add_cart action tocart primary" href="javascript:void(0)" ><?= $block->escapeHtml(__('Add to Cart')) ?> </a>
										<?php else: ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
												<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
												<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
												<?= $block->getBlockHtml('formkey') ?>
												<button type="submit"
														title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
														class="action tocart primary">
													<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
												</button>
											</form>
										<?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php if($_product->getTypeId() == 'bundle'): ?>javascript:void(0)<?php else: ?><?= /* @escapeNotVerified */ $_product->getProductUrl() ?> <?php endif; ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<div class="modal-content" id="modal-content" style="display:none">
	<div class="modal-body" id="bundle_port">
	<input type="hidden" id="product_id" />
	<div class="row" id ="port_div">
		<div class="col-xs-12 margin-xs-b-m">   
			<label>Are you making portability</label><br>
			<input type="radio" name="port" value="yes">Yes<br>
			<input type="radio" name="port" value="no">No<br>
		</div>
    </div>
	<div class="row" id="current_service_div" style="display:none">
		<div class="col-xs-12 margin-xs-b-m">   
			<label>Current service is:</label><br>
			<input type="radio" name="current_service" value="prepaid">Prepaid<br>
			<input type="radio" name="current_service" value="postpaid">Postpaid<br>
		</div>
    </div>
	<div class="row" id ="buy_smartphone_div" style="display:none">
		<div class="col-xs-12 margin-xs-b-m">   
			<label>Would you like to buy a smartphone</label><br>
			<input type="radio" name="buy_smartphone" value="yes">Yes<br>
			<input type="radio" name="buy_smartphone" value="no">No<br>
		</div>
    </div>
	</div>
</div>
<script>
require([
	'jquery',
	'Magento_Ui/js/modal/modal'
], function ($, modal) {
	var optionsVal = {
		type: 'popup',
		responsive: true,
		innerScroll: false,
	};
	var popupData = modal(optionsVal, $('#modal-content'));
	
	$(".bundle_add_cart").on("click", function () {
		var idArray = $(this).attr('id').split('-');
		var id = idArray[1];
		$("#product_id").val(id);
		$("#modal-content").css("display", "block");
		$('#modal-content').modal('openModal');
	});
	
	$("input[type=radio][name=port]").on('click',function () {
		var product_id = $("#product_id").val();
		var port = $(this).val();
		var current_service = '';
		var buy_smartphone = '';
		if(port == 'yes'){
			$("#port_div").css("display", "none");
			$("#current_service_div").css("display", "block");
			$("#buy_smartphone_div").css("display", "none");
		} else {
			var data11 = {product_id: product_id,port: port,current_service: current_service,buy_smartphone: buy_smartphone};
			$.ajax({
					url: "<?php echo $block->getBaseUrl() . 'port/index/index' ?>",
					dataType: 'json',
					showLoader: true,
					type: 'post',
					data: data11,
					success: function (data) {
						window.location.href = data;
					}
				});
		}
	});
	$("input[type=radio][name=current_service]").on('click',function () {
		var product_id = $("#product_id").val();
		var port = $('input[name=port]:checked').val();
		var current_service = $(this).val();
		var buy_smartphone = '';
		$("#port_div").css("display", "none");
		$("#current_service_div").css("display", "none");
		$("#buy_smartphone_div").css("display", "block");
	});
	$("input[type=radio][name=buy_smartphone]").on('click',function () {
		var product_id = $("#product_id").val();
		var port = $('input[name=port]:checked').val();
		var current_service = $('input[name=current_service]:checked').val();
		var buy_smartphone = $(this).val();
		var data11 = {product_id: product_id,port: port,current_service: current_service,buy_smartphone: buy_smartphone};
		$.ajax({
				url: "<?php echo $block->getBaseUrl() . 'port/index/index' ?>",
				dataType: 'json',
				showLoader: true,
				type: 'post',
				data: data11,
				success: function (data) {
					window.location.href = data;
				}
			});
	});
});
</script>
