<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
   ->toHtml() ?>
*/
/* @var $block \Magento\Customer\Block\Widget\Name */
$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
$x='data-validate="{\'validate-apostrophe\':true,required:true}"';
//$x = 'data-validate="{required:true, validate-email:true}"';
          
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$customerId = $customerSession->getCustomer()->getId();
$order = $objectManager->create('Magento\Sales\Model\Order')->getCollection()->addAttributeToFilter('customer_id', $customerId);
?>  
	<?php
	//code
	if($customerSession->isLoggedIn())
	{ ?>
		<div class="form-left">
			<div class="field field-name-firstname required">
				<label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>">
					<span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?></span>
				</label>
				<div class="clearfix">
					<?php if ($prefix): ?>
						<select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
								name="<?php /* @escapeNotVerified */ echo $block->getFieldName('prefix') ?>"
								title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('prefix') ?>"
								class="<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
							<?php foreach ($block->getPrefixOptions() as $_option): ?>
							<?php if(isset($_option) && $_option!=""):?>
								<option value="<?php /* @escapeNotVerified */ echo $_option ?>"<?php if ($block->getObject()->getPrefix() == $_option): ?> selected="selected"<?php endif; ?>>
									<?php /* @escapeNotVerified */ echo __($_option) ?>
								</option>
								<?php endif;?>
							<?php endforeach; ?>
						</select>
					<?php endif; ?>
					<?php if(count($order) > 0) { ?>
					<input type="text" value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>" id="cust_firstname" name="cust_firstname" disabled="true"/>
					<div class="control">
						<input type="hidden" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>"
							   name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>"
							   value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
							   title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
							   class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('firstname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
					</div>
					<?php } else { ?>
					<input type="text" id="cust_firstname"
							   name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>"
							   value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
							   title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
							   class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('firstname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> data-validate="{'validate-french-name':true,required:true}">
					<?php } ?>
				</div>
			</div>
		</div>
		
	<?php } 
	//lastname
	if($customerSession->isLoggedIn()){ ?>
	
	<div class="form-right">
		<div class="field field-name-lastname required">
            <label class="label"  for="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>">
                <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?></span>
            </label>
			<?php if(count($order) > 0) { ?>	
			<input type="text" value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>" id="cust_lastname" name="cust_lastname" disabled="true"/>
			<div class="control">
                <input type="hidden" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>"
                       value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
                       class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('lastname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
            </div>
			<?php } else { ?>
			<input type="text" id="cust_lastname" 
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>"
                       value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
                       class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('lastname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> data-validate="{'validate-french-name':true,required:true}">
            <?php } ?>
        </div>
	</div>
	<?php }
	//code
	?>								
	<?php
	if(!$customerSession->isLoggedIn())
	{ ?>
		<div>
			<div>
				<div class="col-md-3 col-sm-3 col-xs-3 pl0 pr0">
					<label class="Login_form_Txt pull-left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><?php echo $block->escapeHtml(__('Civility')) ?></font></font></label>
				</div>
				<div class="col-md-9 col-sm-9 col-xs-9 pr0">
					<label class="Login_form_Txt pull-left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><?php echo $block->escapeHtml(__('Last Name *')) ?></font></font></label>
				</div>
			</div>
			<div class="clearfix col-lg-12 col-md-12 col-sm-12 col-xs-12 pl0 pr0">
				<div class="col-md-3 col-sm-3 col-xs-3 pl0 pr0">
					<?php if ($prefix): ?>
						<select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
								name="<?php /* @escapeNotVerified */ echo $block->getFieldName('prefix') ?>"
								title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('prefix') ?>"
								class="form-control mobiledrop <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
							<?php foreach ($block->getPrefixOptions() as $_option): ?>
							<?php if(isset($_option) && $_option!=""):?>
								<option value="<?php /* @escapeNotVerified */ echo $_option ?>"<?php if ($block->getObject()->getPrefix() == $_option): ?> selected="selected"<?php endif; ?>>
									<?php /* @escapeNotVerified */ echo __($_option) ?>
								</option>
								<?php endif;?>
							<?php endforeach; ?>
						</select>
					<?php endif; ?>
				</div>
				<div class="col-md-9 col-sm-9 col-xs-9 pr0">
					<input type="text" placeholder="" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>"
						   name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>"
						   value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
						   title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
						   class="form-control Login_box input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('lastname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo  $x; ?>>
				</div>
			</div>
		</div>	
		<?php } ?>
    
	
<?php 
	if(!$customerSession->isLoggedIn())
	{ ?>									
			<div class="clearfix col-lg-12 col-md-12 col-sm-12 col-xs-12 pl0 pr0">
				<label for="lastName"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><?php echo $block->escapeHtml(__('First Name *')) ?></label>
				<div class="control">
					<input type="text" placeholder="" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>"
                       value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
                       class="form-control Login_box input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('firstname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo $x; ?>>
					   <div class="clear"></div>
				</div>
			</div>
	<?php   } ?>