<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see \Magento\Customer\Block\Widget\Dob
 */
?>
<style>
#change-email
{
	display:none;
	pointer-events: none;
   color:white;
   background-color:white;
}
label[for="change-email"]
{
    color:white;
    display:none;
	pointer-events: none;
	background-color:white;
   
}
#testdob
{
	display:none !important;
}
.cus-datepicker .ui-datepicker-trigger{
    right: 496px !important;
    top: 89px !important;
}
</style>
<?php

$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$customerId = $customerSession->getCustomer()->getId();
$order = $objectManager->create('Magento\Sales\Model\Order')->getCollection()->addAttributeToFilter('customer_id', $customerId);

if($customerSession->isLoggedIn()) {
	
    $customerid = $customerSession->getCustomer()->getId(); 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customer = $objectManager->create('Magento\Customer\Model\Customer')->load($customerid);
	  $custdobval = $customer->getData('dob');
	 $date = DateTime::createFromFormat('Y-d-m', $custdobval);
//$date = DateTime::createFromFormat('Y-d-m', $custdobval);
   $custdob  = $date->format('d/m/Y');
?>

<?php if(count($order) > 0) { ?>
<div class="<?php /* @escapeNotVerified */ echo $fieldCssClass; ?>">
    <label class="label" for="<?php echo $block->getHtmlId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left">
        <input type="text" value="<?php echo $custdob; ?>" id="cust_dob" class="form-control" name="cust_dob" disabled="true"/>
    </div>
</div>
<div id="testdob" class="<?php /* @escapeNotVerified */ echo $fieldCssClass; ?>">
    <label class="label" for="<?php echo $block->getHtmlId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left control customer-dob">
        <?php echo $block->getFieldHtml(); ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?php /* @escapeNotVerified */ echo $_message; ?></div>
        <?php endif; ?>
    </div>
</div>
<?php } else { ?>
<div class="field date field-dob required">
<label class="label" for="<?php echo $block->getHtmlId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20 pl0 pull-left control customer-dob cus-datepicker">
        <?php echo $block->getFieldHtml(); ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?php /* @escapeNotVerified */ echo $_message; ?></div>
        <?php endif; ?>
    </div>
</div>
<div id="doberrr" style="color: red;font-size: 12px;padding-top:4px;"></div>
<?php } ?>
<?php }
else
{
?>

			

			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb20 pr40 <?php /* @escapeNotVerified */ echo $fieldCssClass; ?>">	
			<label class="Login_form_Txt pull-left"> <?php /* @escapeNotVerified */ echo $block->getLabel() ?> <span>*</span></label>
				 <div class="control customer-dob">
        <?php echo $block->getFieldHtml(); ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?php /* @escapeNotVerified */ echo $_message; ?></div>
        <?php endif; ?>
		<div id="doberrr" style="color: red;font-size: 12px;padding-top:4px;"></div>
    </div>
	</div>



<?php  } ?>
<script>// <![CDATA[
    require(['jquery'], function ($) {
	    $(document).ready(function() {
			$('#dob').attr('placeholder','JJ / MM / AAAA');
			
		}); 
        
    });
    // ]]>
</script>
