<?php
declare(strict_types = 1);
/**
 * Limesharp_Stockists extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Limesharp
 * @package   Limesharp_Stockists
 * @copyright 2016 Claudiu Creanga
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Claudiu Creanga
 */
?>

<?php /** @var \Limesharp\Stockists\Block\Stockists $block */ ?>
<?php $_store = $block->getCurrentStore(); ?>
<?php $data = $block->getStoresForFrontend(); ?>
<?php $countryList = $block->getCountries(); ?>
<?php $modulePath = "limesharp_stockists/stockist/image/"; ?>
<?php $templateSetting = $block->getTemplateSettings(); ?>

<?php
if ($block->getMapPin()) {

    $mapPin = $block->getMediaUrl() . "limesharp_stockists/" . $block->getMapPin();
} else {

    $mapPin = $block->getViewFileUrl('Limesharp_Stockists::images/map_pin.png');
}
?>
<!-- there are 3 templates, page_width_top has a different html structure -->
<?php if ($templateSetting != "page_width_top"): //if it is full_width_sidebar or page_width_sidebar  ?>

    <div class="parent-stockists <?php echo $templateSetting; ?>">

        <div class="directions-panel">
            <p>Your directions: </p>
            <p class="change-directions">Change to <span class="walking get-directions" data-directions="WALKING">walking, </span><span class="cycle get-directions" data-directions="BICYCLING">cycling</span>, <span class="transit get-directions" data-directions="TRANSIT">public transport</span> or <span class="driving get-directions" data-directions="DRIVING">driving</span>.</p>
            <div class="close"></div>
        </div>

    </div>
    <div class="contacts-store-details">
        <p>
            At DigiCel we are on hand to receive your comments, questions and suggestions.<br>
            Contact us and tell us what we can do for you or how we can improve your shopping experience with us.
        </p>
        
        <div class="store-offices">
            <div class="store-office1">
                <span>Corporate offices:</span><br>
                <span>Tel: <?php echo $block->getTelephone()?></span><br>
                <span><?php echo $block->getAddress() ?></span>
            </div>
            <div class="store-office2">
                <span>Customer Service</span><br>
                <span>Tel: <?php echo $block->getTelephone()?></span><br>
                <span><?php echo $block->getSupportEmail()?></span>
            </div>
        </div>
    </div>
<div class="map-details">
    <p>Our Stores</p>
        <div id="map-canvas" style="height: 100%; width: 100%;"></div>
    </div>
    <div class="store-list">
        <?php $i = 1; ?>
        <?php foreach ($data as $item): ?>

            <img src="<?php echo $block->getMediaUrl() . 'limesharp_stockists/stockist/image/' . $item->getData('details_image') ?>" alt="">
            <p>Store <?php echo $i; ?></p>
            <div class="store-details">
                <span class="store-phone"><?php echo $item->getData('phone'); ?></span><br>
                <span class="store-address"><?php echo $item->getData('address'); ?></span><br>
                <span class="store-city"><?php echo $item->getData('city') . ', ' . $item->getData('country'); ?></span>
            </div>
            <?php
            $i++;
        endforeach;
        ?>
    </div>
<?php else: //if $templateSetting is page_width_top   ?>
<?php endif; ?>

<script type="text/x-magento-init">
    {
    "*": {

    "limesharp_stockists": {
    "moduleUrl" : "contacts",
    "map_styles" : "<?php echo $block->getMapStyles() ?>",
    "map_pin" : "<?php echo $mapPin; ?>",
    "geolocation" : <?php echo json_encode($block->getLocationSettings()) ?>,
    "zoom" : <?php echo json_encode($block->getZoomSettings()) ?>,
    "latitude" : <?php echo json_encode($block->getLatitudeSettings()) ?>,
    "longitude" : <?php echo json_encode($block->getLongitudeSettings()) ?>,
    "radius" : <?php echo json_encode($block->getRadiusSettings()) ?>,
    "template" : "<?php echo $templateSetting; ?>",
    "apiKey" : "<?php echo $block->getApiKeySettings(); ?>",
    "unit" : "<?php echo $block->getUnitOfLengthSettings() ?>",
    "fillColor" : "<?php echo $block->getFillColorSettings() ?>",
    "fillOpacity" : <?php echo json_encode($block->getFillOpacitySettings()) ?>,
    "strokeColor" : "<?php echo $block->getStrokeColorSettings() ?>",
    "strokeOpacity" : <?php echo json_encode($block->getStrokeOpacitySettings()) ?>,
    "strokeWeight" : <?php echo json_encode($block->getStrokeWeightSettings()) ?>,
    "ajaxUrl" : <?php echo json_encode($this->getBaseUrl() . 'locate/ajax/stores/') ?>
    }

    }
    }
</script>
