<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Continue to purchase'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="smart-phone-btm-bdy">
        <div class="box-tocart smart-phone-button-cont">
            <!-- <div class="fieldset"> -->
                <?php if ($block->shouldRenderQuantity()): ?>
                <!--div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               />
                    </div>
                </div -->
                <?php endif; ?>
                <!-- <div class="actions"> -->
                    <button disabled="disabled" type="submit"
                            title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                            class="action primary tocart smart-phone-button"
                            id="product-addtocart-button">
                        <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                <!-- </div> -->
            <!-- </div> -->
        </div>
        <?php if($_product->getAttributeSetId() == 10){ ?>
               
                <div class="row smart-phone-pr-radio" id ="port_div">
                    <input type="hidden" name="upsell_id" id="upsell_id">
                    <div class="col-xs-12 margin-xs-b-m smart-phone-portability">   
                        <span>Are you making portability?</span>
                        <div class="radio-button-cont">
                            <div class="radio-button">
                                <input name="portable" class="portable" type="radio" value="yes"/>
                                <label>Yes</label>
                            </div>
                            <div class="radio-button">
                                <input class="portable" name="portable" type="radio" value="no"/>
                                <label>No</label>
                            </div>
                        </div>
                    </div>
                </div>
            	<div class="row smart-phone-pr-radio" id ="port_div_session" style="display:none">
            		<div class="col-xs-12 margin-xs-b-m smart-phone-portability">   
            			<label>Already portable product in cart. Do you want to remove the existing product?</label><br>
            			<div class="radio-button-cont">
                            <div class="radio-button">
                                <input type="radio" class="portable" name="port_remove" value="yes" />
                                <label>Yes</label>
                            </div>
                            <div class="radio-button">
                    			<input type="radio" class="portable" name="port_remove" value="no" />
                                <label>No</label>
                            </div>
                        </div>
            		</div>
                </div>
                <div class="row smart-phone-pr-radio" id ="service_div" style="display: none;">
                    <div class="col-xs-12 margin-xs-b-m smart-phone-portability">   
                        <label>Current service is:</label><br>
                        <div class="radio-button-cont">
                            <div class="radio-button">
                                <input type="radio" class="service portable" name="service" value="prepaid" />
                                <label>Prepaid</label>
                            </div>
                            <div class="radio-button">
                                <input type="radio" class="service portable" name="service" value="postpaid" />
                                <label>Postpaid</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row smart-phone-pr-radio" id ="contract_div" style="display: none;">
                    <div class="col-xs-12 margin-xs-b-m smart-phone-portability">   
                        <label>How do you want it?</label><br>
                        <div class="radio-button-cont">
                            <div class="radio-button">
                                <input type="radio" id="contract_yes" class="contract portable" name="agree_condition" value="contract" />
                                <label>Contract</label>
                            </div>
                            <div class="radio-button">
                                <input type="radio" id="contract_no" class="contract portable" name="agree_condition" value="prepaid" />
                                <label>Prepaid</label>
                            </div>
                        </div>
                    </div>
                </div>
            	<div class="row smart-phone-pr-radio" id ="contract_div_session" style="display:none">
            		<div class="col-xs-12 margin-xs-b-m smart-phone-portability">   
            			<label>Already contract product in cart. Do you want to remove the existing product?</label><br>
                        <div class="radio-button-cont">
                            <div class="radio-button">
                                <input type="radio" name="contract_remove" class="portable" value="yes" />
                                <label>Yes</label>
                            </div>
                            <div class="radio-button">
                                <input type="radio" name="contract_remove" class="portable" value="no" />
                                <label>No</label>
                            </div>
                        </div>
            		</div>
                </div>
                <div class="row smart-phone-pr-radio" id ="contract_option" style="display: none;">

                    <select name="contract_period" id="contract_period">
                    <option value="6">6 month</option>
                    <option value="12">12 month</option>
                    <option value="18">18 month</option>
                    </select>
                </div>
				
				<?php echo $block->getLayout()->createBlock(\Digicel\Portin\Block\Index\Popup::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                
        <?php } ?>        
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
<script>
require([ 'jquery', 'jquery/ui'], function($){ 
      $('#state,#city,#street,#zip').bind('keypress blur', function() {    
		$('#finalnumber').val($('#state').val() + '' +
                             $('#city').val() + '' +
                             $('#street').val() + '' +
                             $('#zip').val() );

      });
 });
</script>
