<div class="smart-phone-spec-detail">
    <h5>Ratings and Reviews</h5>
    <div class="rating-summary">
        <label>REVIEWS:</label>
        <span>4</span> <i class="fas fa-star"></i> <span>|</span> <a href="#">250 REVIEWS</a> </div>
    <div class="rating-sub-header">Excellent</div>
    <div class="smart-phone-reviews">
        <div class="smart-phone-reviews-content">
            <p> The World's Best &amp; Stylish Smartphone From SAMSUNG. </p>
            <p> Hats Off To The Entire SAMSUNG Design Team For Making This Beautiful Smartphone. The Design Of Galaxy S8 Is Stylish &amp; Cool. The Rear Camera Quality Is Outstanding, In fact It's Best Ever Smartphone Camera Till Now! Front Camera Of Galaxy S8 Is Lovely, It's A Wonderful Selfie Camera For All The Selfie Lovers. Display Quality Is Fantastic </p>
            <a href="#">John Doe</a> </div>
        <div class="smart-phone-reviews-content">
            <p> The World's Best &amp; Stylish Smartphone From SAMSUNG. </p>
            <p> Hats Off To The Entire SAMSUNG Design Team For Making This Beautiful Smartphone. The Design Of Galaxy S8 Is Stylish &amp; Cool. The Rear Camera Quality Is Outstanding, In fact It's Best Ever Smartphone Camera Till Now! Front Camera Of Galaxy S8 Is Lovely, It's A Wonderful Selfie Camera For All The Selfie Lovers. Display Quality Is Fantastic </p>
            <a href="#">John Doe</a> </div>
        <div class="smart-phone-reviews-content">
            <p> The World's Best &amp; Stylish Smartphone From SAMSUNG. </p>
            <p> Hats Off To The Entire SAMSUNG Design Team For Making This Beautiful Smartphone. The Design Of Galaxy S8 Is Stylish &amp; Cool. The Rear Camera Quality Is Outstanding, In fact It's Best Ever Smartphone Camera Till Now! Front Camera Of Galaxy S8 Is Lovely, It's A Wonderful Selfie Camera For All The Selfie Lovers. Display Quality Is Fantastic </p>
            <a href="#">John Doe</a> </div>
        <div class="smart-phone-reviews-content">
            <p> The World's Best &amp; Stylish Smartphone From SAMSUNG. </p>
            <p> Hats Off To The Entire SAMSUNG Design Team For Making This Beautiful Smartphone. The Design Of Galaxy S8 Is Stylish &amp; Cool. The Rear Camera Quality Is Outstanding, In fact It's Best Ever Smartphone Camera Till Now! Front Camera Of Galaxy S8 Is Lovely, It's A Wonderful Selfie Camera For All The Selfie Lovers. Display Quality Is Fantastic </p>
            <a href="#">John Doe</a> 
        </div>
        
    </div>
    <div class="btn-content">
        <button type="button" class="smart-phone-sec-button">Load More Reviews</button>
    </div>
</div>