<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$checkoutSession = $objectManager->create('Magento\Catalog\Model\Session');
echo "port->".$checkoutSession->getPort().'<br>';
echo "current_service ->".$checkoutSession->getCurrentService().'<br>';
echo "buy_smartphone->".$checkoutSession->getBuySmartphone();
if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
