<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catalogSession = $objectManager->create('Magento\Catalog\Model\Session');
echo "port->".$catalogSession->getPort().'<br>';
echo "current_service ->".$catalogSession->getCurrentService().'<br>';
echo "buy_smartphone->".$catalogSession->getBuySmartphone(); 

if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
